### ISSUE TITLE
Waterfox 2020.07.2.1 bug: Search bar on the left all of a sudden, density reset.

### ISSUE THREAD

**Issue by Peacock365** [MrAlex94/Waterfox#1715] opened 2020-08-15 15:16 UTC
Just updated to version 2020.07.2.1 using the internal updater: The effect was that the search bar suddenly appeared at the left side of the window, removing it under about:preferences#search doesn't work. The icon density also got reset from the previous "compact" to "normal". macOS 10.15.6 Catalina, if that matters.

**Comment by Peacock365** [comment] 2020-08-15 19:25
Man, @hawkeye116477 can't help but mess up Waterfox on macOS all the time, this is yet another example: https://github.com/MrAlex94/Waterfox/issues/1630#issuecomment-667491670

See, I get it, you like Linux and all, but macOS is a FAR bigger platform than Linux, Waterfox presumably has more Mac users as well. Please, for the love of god, stop meddling with anything concerning the UI. It is bound to break the Mac version of Waterfox.

**Comment by hawkeye116477** [comment] 2020-08-15 19:29
`mess up Waterfox on macOS all the time `

Sorry, as I told I don't have Mac, but @MrAlex94 have it and he accept PR, so he should test that again properly before accepting, don't blame me only. 

`Please, for the love of god, stop meddling with anything concerning the UI.`

Same thing I could wrote to you, stop adding changes to about:config, cuz it breaks sites. It's open-source project, anyone can submit changes and in both cases the final decision belongs to MrAlex.

**Comment by MrAlex94** [comment] 2020-08-15 19:54
2020.07.2.1 reverted previous changes to the toolbar structure, but shouldn't have had anything to do with actually changing already existing components or their placement.

**Comment by Peacock365** [comment] 2020-08-15 19:59
Okay, if this makes you happy, I am also blaming @MrAlex94 now, for his apparent neglect of testing with a clean profile. But then, knowing this, stop submitting UI-related patches please if you can't test them on all platforms, since you do know now that @MrAlex94 won't test them, either. However, I won't cut you some slack, knowing that it is entirely possible to setup a macOS VM (at least an old version should be possible) on Linux via VirtualBox. What is your excuse for not doing this, it doesn't cost you a dime (both VirtualBox and macOS licenses are free of charge).

My frustrations with this project continue to grow. @MrAlex94 has apparently given up on integrating language packs with Waterfox Current, reducing its appeal to non-native speakers. And no, offering some language pack somewhere is not substitute for including them. @MrAlex94 is not even capable of fixing the New Tab button in the Australis themes, they have been broken ever after Waterfox 68.0b1. Should be a simple CSS fix, even my granny who never coded would have figured it out by now. I suspect that @MrAlex94 has a full time job unrelated to Waterfox and runs this entire operation as a hobby, which would somewhat explain his inactivity, but a fix like that should be doable even for the most hobbiest of hobby projects, we are entering the realm of "not caring" here.

I was hopeful that the System1 takeover would lead to renewed activity and some professional support for this project (literally the only positive thing I hoped would come out of this acquisition), but apparently not. Isn't System1 interested in their own products? Anyway, I am switching to Ungoogled Chromium now, at least this one is stable and doesn't mess up stuff all the time. 

> Same thing I could wrote to you, stop adding changes to about:config, cuz it breaks sites. It's open-source project, anyone can submit changes and in both cases the final decision belongs to MrAlex.

Nonsense. The only flag that had minimal impact(!) was the one that had something to do with no longer offering GPU debugging information. Someone then compained that it broke some GPU test on the Nvidia(!) website, i.e. the website of a GPU manufacturer. Oh, heavy stuff indeed, to fix this issue that should affect 0.000000000000000001% of websites we are now making fingerprinting easier again. Great stuff right there, I would have declared the issue of that one guy RESOLVED WONTFIX based on it only affecting a minuscule number of websites.

> 2020.07.2.1 reverted previous changes to the toolbar structure, but shouldn't have had anything to do with actually changing already existing components or their placement.

I didn't have the search bar enabled before, but now it appears at the left side of the screen, and is non-removable. The icon density was also reset. Anyway, giving up on this project now. Wish you all the best regardless.

**Comment by hawkeye116477** [comment] 2020-08-15 20:07
>  What is your excuse for not doing this, it doesn't cost you a dime (both VirtualBox and macOS licenses are free of charge).

Mhmm, where I can download macOS for free? As I read, it's free only if I buy mac Computer, so it's not really free.

> if you can't test them on all platforms, since you do know now that @MrAlex94 won't test them, either

Yes, I have a magic ball and I knew about it...

> even my granny who never coded would have figured it out by now

So why she didn't submit Pull Request if she know how to fix that?

**Comment by Peacock365** [comment] 2020-08-15 20:13
> Mhmm, where I can download macOS for free? As I read, it's free only if I buy mac Computer, so it's not really free.

I hope you are joking, you can literally get installers online, even from the Apple website itself. They also sell them on eBay for like $10.

> Yes, I have a magic ball and I knew about it...

Well, you do know now for sure. But this should have been apparent after the first UI-destroying bug you introduced and that got merged regardless. Spare us "Third time is the charm!", **please**.

> So why she didn't submit Pull Request if she know how to fix that?

Hm, I don't know, maybe because someone who claims to maintain a browser and runs this entire repo could be expected to fix such a simple issue without outside interference, in a time span of **1 year**. But hey, maybe I am just impatient, who knows.

**Comment by hawkeye116477** [comment] 2020-08-15 20:31
> I hope you are joking, you can literally get installers online, even from the Apple website itself.

So maybe I don't know about something, but user on quora says that's not free and I need to buy something from Apple Store to have macOS, so at least legally I can't download it for free. I can only download updates for free.

---------------------------------------------------------
@Peacock365 Waterfox is open-source, so if you don't like something, then you could fork it and provide your changes, if you know how to do that, but from what I read from you, I'm sure you can handle it and provide the best fox browser in the world :smile:.

**Comment by Peacock365** [comment] 2020-08-15 20:39
> So maybe I don't know about something, but user on quora says that's not free and I need to buy something from Apple Store to have macOS, so at least legally I can't download it for free.

You can buy or download Mac OS X 10.10, which even a weak ass Linux PC should be able to virtualize successfully. What do you think the entire Hackintosh community is doing? Please spare me excuses, even if we go along with the theory that you need to buy a Mac to run macOS, which you don't, how much is a Mac mini 2009 these days (which runs everything up to OS X 10.11 El Capitan)? Does the amount of money required exceed $50? Maybe someone donates one to you at the flee market at this point...

> Waterfox is open-source, so if you don't like something, then you could fork it and provide your changes, if you know how to do that, but from what I read from you, I'm sure you can handle it and provide the best fox browser in the world 😄.

A laughing smiley won't magically make the apparent incompetence and / or laziness here disappear, which extends as far as not being able to come up with a simple CSS fix. And if I had to fork something, I'd take the main Firefox repo, disable the privacy-invading stuff, replace the branding and call it a day. I call this Earthfox, then. However, contrary to you, I would not attempt to meddle with stuff I am not competent enough to meddle with, and for which I lack the testing capabilities.

**Comment by InvisibleManX** [comment] 2020-08-16 02:27
@hawkeye116477 
@MrAlex94 

I just got the same issue after I changed the search settings to "Use the address bar for search and navigation" and restarted my browser. 

I managed to fix it for now only by creation of a new profile... But I'm pretty sure that this update simply isn't compatible with some option available in about:config 

I didn't change many, but I did change a few after installing the browser initially (like opening search result in a new tab) because by default a some things are inconvenient to use. 

But everything worked like a charm before the update 2020.07 that has some changes related to the toolbar listed in its changelog... So it indeed broke something.

And I see that nobody is gonna try to figure out what happened...

**Comment by InvisibleManX** [comment] 2020-08-16 02:49
@hawkeye116477 
@MrAlex94 

**I just found a fix to this whole thing!**

Apparently the consecutive updating from 2020.07 to 2020.07.1 / 2020.07.2 / 2020.07.2.1 result in a corrupted file "xulstore.json" for some people.

**The fix:** 
You just need to close the browser, then remove the file "**xulstore.json**" from your user profile folder and start a browser again. 

Everything works!
And after closing a browser again a new xulstore.json file is created, but it's not broken anymore! 

I noticed, that the broken xulstore.json was noticeably bigger than the newly created one that isn't broken anymore apparently. 

P.S. To everyone who tries to fix this thing, you can find that profile folder by typing `about:support` in the address bar, hitting Enter, and then clicking the "Open Folder" button in the "Profile Folder" section in the table there.

**Comment by hawkeye116477** [comment] 2020-08-16 08:02
@InvisibleManX I haven't that problem, but it's good that there are still people who want to help instead of only playing smart guy.

**Comment by Peacock365** [comment] 2020-08-16 08:19
@InvisibleManX 

Thank you, this fixed it for me. Hopefully a fix will arrive in time for others as well (though I am not all too sure about the "in time" part).

@hawkeye116477 

You are pretty sassy considering that you alone caused this, you should be the one to fix this as well, but alas "no testing capabilities".

**Comment by hawkeye116477** [comment] 2020-08-16 08:54
@Peacock365 I know that's my fault, but that doesn't mean that you must behave as you showed. It's free open-source project, you didn't pay anyone, someone taking his time for free, so you should be more respectful for people who add changes to this project.  It's a pity, seems that you still don't understand my words and how open-source project works.

**Comment by Peacock365** [comment] 2020-08-16 09:31
@hawkeye116477

I am not unappreciative of your efforts outside of the UI. Stop meddling with the UI, and this will automatically brighten the day of users like me again. That's really all I ask for.

**Comment by hawkeye116477** [comment] 2020-08-16 09:42
@Peacock365 Seems that you still don't understand my words and how open-source project works.

**Comment by Peacock365** [comment] 2020-08-16 09:44
Seems like you don't understand how to handle frontend code properly. Also, why should I clean up your mess? It's either @MrAlex94 or you. I am not interested in forking anything myself, and I fail to see how this would excuse, let alone fix, bugs in the Waterfox repo.

**Comment by InvisibleManX** [comment] 2020-08-16 16:08
@Peacock365 
Okay, let's calm down here. :) 

It is indeed an open-source project, and while the situation is frustrating, we all are humans and we can all make mistakes. 

Testing for bugs can't happen without involvement of a good amount of users, which is what happened here. The problem seem to be a tricky one, not that straightforward to solve.

And UI is a part of any brower, so "meddling" is necessary to have progress and have browsers evolve futher.

**Comment by InvisibleManX** [comment] 2020-08-16 16:17
@hawkeye116477 

By the way, turns out that the file "xulstore.json" is known to cause problems in general and might need some occasional resetting, according to the official support recommendations for Firefox. 

More details are in this comment: [https://github.com/MrAlex94/Waterfox/issues/1716#issuecomment-674545953](https://github.com/MrAlex94/Waterfox/issues/1716#issuecomment-674545953)

**Comment by Peacock365** [comment] 2020-08-16 21:34
@InvisibleManX 

I appreciate you finding out that it has something to do with xulstore.json, deleting this and starting up Waterfox again fixed the issue for me. However, this does not mean that it is fixed for everyone else out there as well, which is why I keep this open.

> And UI is a part of any brower, so "meddling" is necessary to have progress and have browsers evolve futher.

Ah yes, nothing like a general wisdom applied to a situation where it doesn't fit. The UI of Waterfox was totally fine and 100% functional before @hawkeye116477 came in and started meddling with it (I am consciously avoiding "working on it" here, because meddling is what he does). This needs to stop, unless he can test his changes on all platforms in some manner. Everything else will just make life more miserable for everyone not using Waterfox on Linux, i.e. 90%+ of all Waterfox users.

Moreover, stuff like "It's free, so don't complain." or "We are all volunteers here." coming from that guy doesn't fly with me, because I only hear those excuses when something goes wrong, and I know why that is: Convenient blah blah after a major mistake, I will have none of it.

**Comment by InvisibleManX** [comment] 2020-08-17 00:21
@Peacock365 
So you chose to remain hostile. 
I guess, it's your right, as a free person.

**Comment by InvisibleManX** [comment] 2020-08-17 00:24
I do agree with one thing though. Yes, in general, testing of any changes should be done on all platforms before its released as an official update. If that doesn't happen, it's not a good approach.

**Comment by Peacock365** [comment] 2020-08-17 07:05
@InvisibleManX 

You mistake my frustration for "hostility", I am just fed up with @hawkeye116477 always introducing UI-breaking bugs on platforms that are not Linux. There are only two options going forward:

1) He stops meddling with the UI altogether, which is what I would suggest, or
2) @MrAlex94 starts testing his commits in earnest on all platforms.

I don't think the latter is what is going to happen, so I implore him to consider the former. That's about it.

**Comment by hawkeye116477** [comment] 2020-08-17 08:33
I could continue that conversation and explain how development process works, but I saw what Peacock wrote on other parts of the Internet and seems that talking with him doesn't make much sense.

**Comment by MrAlex94** [comment] 2020-08-17 09:00
> Okay, if this makes you happy, I am also blaming @MrAlex94 now, for his apparent neglect of testing with a clean profile.

That is how I test, and the issue you are reporting, nor the issue that 2020.07.2.1 fixed occurred during that.

> @MrAlex94 has apparently given up on integrating language packs with Waterfox Current, reducing its appeal to non-native speakers. And no, offering some language pack somewhere is not substitute for including them. 

Well, Mozilla changed the way language packs worked (from DTD to fluent), and considering the vast amount of other projects, it wasn't highest priority integrating them. I did not want to package like I did for `Classic`, considering how much it bloats the distribution size.

@MrAlex94 is not even capable of fixing the New Tab button in the Australis themes, they have been broken ever after Waterfox 68.0b1. Should be a simple CSS fix, even my granny who never coded would have figured it out by now. I suspect that @MrAlex94 has a full time job unrelated to Waterfox and runs this entire operation as a hobby, which would somewhat explain his inactivity, but a fix like that should be doable even for the most hobbiest of hobby projects, we are entering the realm of "not caring" here.

Ah there we go, surely if it's a simple fix, you will contribute it? That _is_ one of the benefits of Waterfox being open source. Secondly that last comment clearly shows lack of understanding of the software development process. Code contribution frequency != amount of work done. Do you think all the infrastructure and planning happen instantaneously? 

> I was hopeful that the System1 takeover would lead to renewed activity and some professional support for this project (literally the only positive thing I hoped would come out of this acquisition), but apparently not. Isn't System1 interested in their own products?

Well, growing and scaling a team is difficult and takes time. Also, you may have noticed the global pandemic that has been happening? It is not helping at all...

> It is indeed an open-source project, and while the situation is frustrating, we all are humans and we can all make mistakes.

@InvisibleManX, much appreciated for the rational response.

@Peacock365, you are being hostile. Clearly your frustrations are manifesting as such. Honestly, unless you want to actually contribute fixes or change the way you speak to everyone, it is best you do not comment at all.

Now, in regards to the last few issues cropping up, I do test on all platforms. Unfortunately I don't test all customisation methods which is why this slipped through. It is not ideal, but so far is as good as it's going to get until the team grows large enough and we get proper QA set up.

@hawkeye116477, @InvisibleManX, thank you for your contributions - they are appreciated.

**Closed as completed by MrAlex94** 2020-08-17 09:00 UTC
Labels: bug

**Comment by Peacock365** [comment] 2020-08-17 09:44
> I did not want to package like I did for Classic, considering how much it bloats the distribution size.

Yes, those 30 MB really pose a problem considering the size of today's HDDs and SSDs and the speed of most Internet connections. Jeez, anyway.

> Ah there we go, surely if it's a simple fix, you will contribute it?

Why don't you? That 1 year worth of time surely was a big enough time frame. But hey, I guess it is progress to even get a reply from you, after having been ignored for the last few times I mentioned this. Kudos.

> Code contribution frequency != amount of work done.

The only difficult thing you do is to apply current Firefox security updates to Classic. Applying them to Current just reflects what Mozilla is doing to FF 68.x ESR anyway. How stupid do you think I am? I mean, seriously. You are doing the absolute minimum at times. Not even a minimal CSS fix gets done.

> Also, you may have noticed the global pandemic that has been happening? It is not helping at all...

Implying that it was ever planned. I suspect that you will be continuing to maintain Waterfox as a one man shop the same way you do now, and after your Bing contract runs out, switch it to StartPage to generate money for System1. Nothing wrong with that per se, but if you manage to do anything more than that, feel free to call me Emperor of China going forward.

> you are being hostile. Clearly your frustrations are manifesting as such.

And you throw a temper tantrum at the moment. You just closed all my open pull requests, which have been sitting there for ages (implying that you at least considered using them), despite having to apply the changes proposed there anyway in the future. If that is not a temper tantrum, then I don't know what is. Care to restore rational behavior? You may not like my tone here (who likes truthful statements about existent problems), but the information relayed here by me is 100% accurate.

> I do test on all platforms
> I don't test all customisation methods

Choose one.

Anyway, have a good time, Ungoogled Chromium is where it's at now for me. Hopefully you will take care of the bug here, instead of just closing the issue in a fit of I don't know what, rage? Have a nice day.

> I saw what Peacock wrote on other parts of the Internet

Care to elaborate, or is this just dirt throwing now? I posted nothing I need to be ashamed for so far. The time you invested in skimming through my prior comments could have went into learning how to do proper frontend development and testing.

**Comment by MrAlex94** [comment] 2020-08-17 10:36
I understand your frustrations, but look at the way you're talking. It's hardly courteous.

> Yes, those 30 MB really pose a problem considering the size of today's HDDs and SSDs and the speed of most Internet connections. Jeez, anyway.

It actually has been a complaint fairly often. And considering most of the Waterfox user base is in the US (which famously has low bandwidth on average for how large it is), those measly megabytes do matter. But ignoring size, all those language packs loading as they do on Classic does affect startup performance. 

> The only difficult thing you do is to apply current Firefox security updates to Classic. Applying them to Current just reflects what Mozilla is doing to FF 68.x ESR anyway. How stupid do you think I am? I mean, seriously. You are doing the absolute minimum at times. Not even a minimal CSS fix gets done.

I mean you clearly missed: Do you think all the infrastructure and planning happen instantaneously? Also, We've done a hell of a lot of work on ESR78, even if it's not public yet. Two points being NPAPI support again and reproducible builds including getting cross-compiling to work for WebRTC. Not quite nothing is it?

Also, just look at how aggressive that comment is. You are not privy to many things, yet you are so hostile and acting omniscient. I am hardly resting on my laurels. Or do you also think the hiring and on-boarding process are easy?

> Implying that it was ever planned. I suspect that you will be continuing to maintain Waterfox as a one man shop the same way you do now, and after your Bing contract runs out, switch it to StartPage to generate money for System1.

What? Who do you think does the DevOps and code contributions? Wasn't all just me, System1 has been contributing massively. Also, the Bing partnership is via System1, it's not going anywhere. Once again, clear lack of understanding. And do you seriously think the global pandemic that has put almost every country on earth into lock downs hasn't had an affect on hiring and work...?

> And you throw a temper tantrum at the moment. 

Actually you'll notice I've been combing through issues this morning as well as closing your requests. I closed your requests because they are all config options, and it is planned to go through them anyway [1](https://github.com/MrAlex94/Waterfox/projects/2#card-42198117). Also, you failed to answer why some of the options you've changed should be used. 

> Choose one.

Well, testing the bare minimum on all platforms clearly isn't the same as testing all customisations.

> Anyway, have a good time, Ungoogled Chromium is where it's at now for me. 

Hopefully you are more respectful to the developers of that project. Please do not come back unless your attitude changes.

**Comment by Peacock365** [comment] 2020-08-17 11:12
> It actually has been a complaint fairly often.

Surely this is worse than leaving all those who don't speak English as their native language without language pack. Set your priorities straight.

> Do you think all the infrastructure and planning happen instantaneously? (...) Or do you also think the hiring and on-boarding process are easy?

Not instantaneously, no. But you talking about building up a team and expanding on infrastructure is as old as Waterfox itself, without it having born any fruit so far. Excuse me if I take this with a grain of salt at this point.

> Not quite nothing is it?

It's more than nothing.

> What? Who do you think does the DevOps and code contributions?

Mostly Mozilla devs with you applying them, or so this repo says.

> Wasn't all just me, System1 has been contributing massively.

Where? Asking out of curiosity.

> And do you seriously think the global pandemic that has put almost every country on earth into lock downs hasn't had an affect on hiring and work...?

The pandemic seems to have resulted in everything staying as it was. Even minor but regular contributions tracing back to System1 would change that impression.

> Actually you'll notice I've been combing through issues this morning as well as closing your requests.

Hm, the issue count is not significantly lower now. The pull requests of @hawkeye116477 are still open... But who likes to admit to having thrown a hissy fit, right? It's OK.

> and it is planned to go through them anyway

Then why close them? I know...

> Also, you failed to answer why some of the options you've changed should be used.

Why explain the self-explanatory? The options I changed there are not that complex to grasp.

> Well, testing the bare minimum on all platforms clearly isn't the same as testing all customisations.

Both are intertwined in the issues I reported, please do not draw an artificial line here.

> Hopefully you are more respectful to the developers of that project.

Hell, YES! I have respect for them, because they manage their repos competently and don't introduce breaking bugs into their builds, implying that they test them. They are also friendly to users and contributors alike.

> but look at the way you're talking. It's hardly courteous.
> Also, just look at how aggressive that comment is.

Respect needs to be earned (or at least not lost), my dear. I was willing to deal with you courteously, but what did you do? You ignored my bug reports, and when I voiced my problem more clearly and with less sugarcoating, you threw a childish hissy fit and closed this issue as well as all my pull requests. How was that "courteous"? Being a bit less hypocritical would be healthy, especially when the problem I reported here was and still is real. Instead you ramble on and on about my supposedly insulting style (after having ignored prior reports of mine, no less), instead of getting any fix out. Real work is where it's at, when your competence in a) responding to and b) actually fixing reported issues increases, I promise my respect for you will know no limits.

> Please do not come back unless your attitude changes.

Don't worry, I won't until you fix your stuff.

**Comment by Peacock365** [comment] 2020-09-04 13:40
New Waterfox version... Nothing new in the west. New tab button in Australis tehme still not fixed, tabs on bottom still causes the Close / Minimize / Maximize buttons to vanish on macOS. But yeah, I was totally wrong here of course. @MrAlex94 will surely fix those...
