### ISSUE TITLE
Reddit dropdowns and buttons not working

### ISSUE THREAD

**Issue by c33s** [MrAlex94/Waterfox#1597] opened 2020-06-02 23:25 UTC
**Describe the bug**
reddit is unusable. javascript error (see additional context. not sure if opening a new issue is correct or if it's a user agent problem https://github.com/MrAlex94/Waterfox/issues/985

today i noticed that i can't post in reddit any more. buttons are disabled, drop downs don't work.

tested it on a fresh profile without extensions and with chromium. doesn't work on waterfox (my default profile & fresh profile) but works on chromium.

**To Reproduce**
1. Go to https://www.reddit.com/
2. Click on 'the upper right account menu'

**Expected behavior**
there should be a dropdown with for example "night mode" in it.

**Screenshots**

**My configuration**
 - Device: pc
 - OS: Windows
 - Version: classic 2020.05

**Additional context**
```
ReferenceError: globalThis is not defined[Learn More]  Governance~Reddit.f630e03a1a7ec31e179a.js:1:16099
	o https://www.redditstatic.com/desktop2x/Governance~Reddit.f630e03a1a7ec31e179a.js:1:16099
	i https://www.redditstatic.com/desktop2x/Governance~Reddit.f630e03a1a7ec31e179a.js:1:16203
	./src/lib/reCaptchaEnterprise/index.ts/m< https://www.redditstatic.com/desktop2x/Governance~Reddit.f630e03a1a7ec31e179a.js:1:18506
	./src/lib/reCaptchaEnterprise/index.ts https://www.redditstatic.com/desktop2x/Governance~Reddit.f630e03a1a7ec31e179a.js:1:17067
	i https://www.redditstatic.com/desktop2x/runtime~Reddit.ef269b616d9dec359dcf.js:1:594
	./src/reddit/index.tsx https://www.redditstatic.com/desktop2x/Reddit.c57fe61fb653d016c16d.js:1:285160
	i https://www.redditstatic.com/desktop2x/runtime~Reddit.ef269b616d9dec359dcf.js:1:594
	t https://www.redditstatic.com/desktop2x/runtime~Reddit.ef269b616d9dec359dcf.js:1:430
	o https://www.redditstatic.com/desktop2x/runtime~Reddit.ef269b616d9dec359dcf.js:1:293
	<anonymous> https://www.redditstatic.com/desktop2x/vendors~Chat~Governance~Reddit.5d28902dc13fc796ac2e.js:1:2
```

**Comment by hawkeye116477** [comment] 2020-06-03 10:29
This is duplicate of #1551 and fix is already commited, will be in next version.

**Comment by MrAlex94** [comment] 2020-06-03 19:04
2020.06 is out, please re-open if still have the issue.

**Closed as completed by MrAlex94** 2020-06-03 19:04 UTC
Labels: bug
