### ISSUE TITLE
Waterfox 2020.01.01 Current does not start on *buntu 18.04 LTS

### ISSUE THREAD

**Issue by PaeNx** [MrAlex94/Waterfox#1393] opened 2020-02-09 09:25 UTC
When starting Waterfox 2020.01.01 Current on Kubuntu 18.04 LTS the application immediately terminates showing the following error message:

```
XPCOMGlueLoad error for file /opt/waterfox/libmozsandbox.so:
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/waterfox/libmozsandbox.so)
Couldn't load XPCOM.
```

**Comment by laniakea64** [comment] 2020-02-09 13:05
Duplicate of https://github.com/MrAlex94/Waterfox/issues/1128

**Comment by PaeNx** [comment] 2020-02-09 14:37
This is not a duplicate. 2020.01.01 wasn't even released when #1128 was reported.

**Comment by laniakea64** [comment] 2020-02-09 19:22
> 2020.01.01 wasn't even released when #1128 was reported.

This isn't new in 2020.01.1.  This has been an ongoing issue with official Linux builds of Waterfox Current for a while.

**Comment by PaeNx** [comment] 2020-02-09 20:00
This is a critical bug in a new release and needs to be fixed. The fact that the bug existed in previous releases is not relevant for this report.

**Comment by hawkeye116477** [comment] 2020-02-10 09:34
@PaeNx Duplicating post rather won't help. Anyway, on Waterfox's site is written that glibc 2.28 is required, Ubuntu 18 has 2.27, so...

As a replacement, I could recommend you my package => `https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-current-kpe`

Here are source files if you're interested:
```
https://build.opensuse.org/package/show/home:hawkeye116477:waterfox/waterfox-current-kpe
https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage
```

My package is compiled with PGO and LTO, so should be little faster than official.

If you rather wanted more portable package, then there is also AppImage:
`https://appimage.github.io/Waterfox_Current/`.

**Comment by ilu33** [comment] 2020-02-13 15:43
Same on debian10, see https://github.com/MrAlex94/Waterfox/issues/1356#issuecomment-585808751

**Closed as completed** 2021-05-27 12:00 UTC
Labels: bug
