### ISSUE TITLE
Update to 6.5.1 failed on Linux

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#3610] opened 2024-11-09 17:52 UTC
### What happened?

When I checked Help -> About it said that release 6.5.1 was available.

I clicked to download the update, but when I restarted Waterfox, it failed to reappear.

I tried running it from a terminal, but got the following error message:

```
richardt@Pavilion:~ $ waterfox
/opt/waterfox/updater: error while loading shared libraries: libmozsqlite3.so: cannot open shared object file: No such file or directory
```

Edit: I am using Mint 22.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell

```

**Comment by ghost** [comment] 2024-11-09 18:38
I have just done a full install of 6.5.1 and it appears to be working.

**Comment by KrzysztofMr** [comment] 2024-11-09 18:39
I've got the same issue in Debian 12. Had to 'downgrade' to v6.5.0

**Comment by TruthInFiction** [comment] 2024-11-09 19:03
I've run into the same problem with Mint 21.3.

**Comment by T0nd0Tara** [comment] 2024-11-09 19:09
I have got the same problem with ubuntu 24.04

**Comment by tgolightly** [comment] 2024-11-09 19:31
I am experiencing the same issue on two of my laptops one running kubuntu 24.04 and kde neon 23.x.

**Comment by krivine** [comment] 2024-11-09 20:23
Same here. Mint 21.3

**Comment by Mycohl** [comment] 2024-11-09 21:58
Same issue on Mint 22.

**Comment by csylvain** [comment] 2024-11-10 02:43
problem is updater doesn't find libmozsqlite3.so in the current directory.

workaround:

$ LD_LIBRARY_PATH=. waterfox

(see output of "$ ldd updater")

**Comment by jcea** [comment] 2024-11-10 03:44
I was going to post the same workaround that @csylvain  but he/she/it was faster :-).

That workaround is only needed during the upgrade. After you are running 6.5.1, just close it and launch Waterfox like you always do.

**Comment by thecnoNSMB** [comment] 2024-11-10 03:50
Issue occurs on Nobara 40. I'm honestly surprised that this failure state is even possible.

**Comment by N8ouy** [comment] 2024-11-10 05:23
Please explain or give an example of "$ LD_LIBRARY_PATH=. waterfox"  After a 16 hour shift, I am not really here.
 never mind...... The ./ is what I forgot when using the cli   

/waterfox$  LD_LIBRARY_PATH=. ./waterfox

Thank you for finding this!

**Comment by Ketrel** [comment] 2024-11-10 06:37
I have/had this issue on Arch, with the browser manually installed from the .bz2 download on the website.

**Comment by kkds1999** [comment] 2024-11-10 09:47
Trying the LD_LIBRARY_PATH=. ./waterfox option but not working for me. In the waterfox download directory if i do:

`LD_LIBRARY_PATH=. ./waterfox`

and afterwards `ldd updater | grep libmozsqlite3.so` i get `libmozsqlite3.so => not found`

Trying to run waterfox from terminal gives:
`/home/xxx/Downloads/waterfox/updater: error while loading shared libraries: libmozsqlite3.so: cannot open shared object file: No such file or directory`

**Comment by ibeladi-mrsool** [comment] 2024-11-10 12:15
I tried `LD_LIBRARY_PATH`, but it did not work for me either, I am on Linux Mint 22

However, I found another workaround, it may or may not work for you:
1. Launch the browser in first-startup mode, `/home/YOUR_PATH/waterfox --first-startup`
2. Go to the 3-dash icon, then `Help`, then `Troubleshoot Mode`, and then `restart` the browser, then `Open`

**Comment by kkds1999** [comment] 2024-11-10 12:24
> I tried `LD_LIBRARY_PATH`, but it did not work for me either, I am on Linux Mint 22
> 
> However, I found another workaround, it may or may not work for you:
> 
> 1. Launch the browser in first-startup mode, `/home/YOUR_PATH/waterfox --first-startup`
> 2. Go to the 3-dash icon, then `Help`, then `Troubleshoot Mode`, and then `restart` the browser, then `Open`

Excellent, thank you. That is now working for me on Mint 22 as well. I also disabled auto update option as well.

**Comment by Ketrel** [comment] 2024-11-10 20:22
If you're using `LD_LIBRARY_PATH=.`  

1. Try `./` rather than just `.`
2. Make sure you're IN the waterfox directory that contains that .so file when you do this

(deleted/reposted because formatting was broken, and editing wasn't fixing it)

**Comment by Enkidu70** [comment] 2024-11-10 20:59
Same here (Mint 21.3) but workaround worked.

**Comment by hiiiha** [comment] 2024-11-12 01:39
Reproducible here. A full new install works and the profile remained

**Comment by MrAlex94** [comment] 2024-11-13 14:31
Hi all,

Just a note I am aware of this issue, and so are Mozilla - this seems to be an upstream issue that we're all investigating. Doing my best to work with them on this as quickly as possible.

I do apologies about this!

**Comment by N8ouy** [comment] 2024-11-16 02:40
Stranger things have been known to happen.  Thank you for digging into it.

**Comment by Ketrel** [comment] 2024-11-16 02:41
Sounds like adding an rpath to the updater to point to . would work

**Comment by explor202** [comment] 2024-11-16 14:52
Is this issue restricted to Linux installs?

**Comment by Mycohl** [comment] 2024-11-19 21:09
> Hi all,
> 
> Just a note I am aware of this issue, and so are Mozilla - this seems to be an upstream issue that we're all investigating. Doing my best to work with them on this as quickly as possible.
> 
> I do apologies about this!

BS. The "upstream" bug was from 8 years ago.

https://bugzilla.mozilla.org/show_bug.cgi?id=1292050
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/18900

It was fixed in affected projects 8 years ago.

This is a regression. One of you hit the wrong button, and when you're called out on it, you flag it as abuse. Clown show.

**Comment by explor202** [comment] 2024-11-19 21:16
> > Hi all,
> > Just a note I am aware of this issue, and so are Mozilla - this seems to be an upstream issue that we're all investigating. Doing my best to work with them on this as quickly as possible.
> > I do apologies about this!
> 
> BS. The "upstream" bug was from 8 years ago.
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1292050 https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/18900
> 
> It was fixed in affected projects 8 years ago.
> 
> This is a regression. One of you hit the wrong button, and when you're called out on it, you flag it as abuse. Clown show.

No worries! I saw this noted as an issue with Linux and wasn't sure if it was restricted to just that OS. I will wait for a fix to be rolled out. Thanks!

**Comment by MrAlex94** [comment] 2024-11-20 10:09
> > Hi all,
> > Just a note I am aware of this issue, and so are Mozilla - this seems to be an upstream issue that we're all investigating. Doing my best to work with them on this as quickly as possible.
> > I do apologies about this!
> 
> BS. The "upstream" bug was from 8 years ago.
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1292050 https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/18900
> 
> It was fixed in affected projects 8 years ago.
> 
> This is a regression. One of you hit the wrong button, and when you're called out on it, you flag it as abuse. Clown show.

That code path doesn't even exist anymore: https://searchfox.org/mozilla-esr128/source/toolkit/xre/nsUpdateDriver.cpp.

And since this affects only ESR128.x builds and not previous ones (ESR115.x), with no build-system changes on my end, nor touching of the updater code on my side, bar the renaming of mozilla -> waterfox/browserworks, is it not a fair assumption that it's an upstream issue? 

Also no one has flagged this as abuse, a very odd comment.

**Comment by MrAlex94** [comment] 2024-11-20 15:55
> Sounds like adding an rpath to the updater to point to . would work

To this point, I can add a build step that uses [patchelf](https://github.com/NixOS/patchelf), which sets `rpath` to `.` for the `updater` executable. My only concern is if there are any unintended consequences of doing so? I've tested it locally myself and the updater now runs.

**Comment by Ketrel** [comment] 2024-11-20 16:18
I think if you use patchelf you'd want to use $ORIGIN not .

As far as I know unless you're wiping out an existing rpath, you'd just be modifing the library search path for the one binary.  So the only thing I could think of offhand is that there's another library along side that should not be loaded, but calling it with LD_LIBRARY_PATH would trigger anything like that too.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ketrel** [comment] 2024-11-20 16:20
Also think if using patchelf you'd want to set runpath over rpath.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MrAlex94** [comment] 2024-11-20 22:13
Thanks for that information, very useful. Will help point me in the right direction, hopefully by the time for next release as I don't want to push out *another* Linux update that doesn't properly work.

tarballs really aren't the best method of distribution anyway, but they have their place.

**Comment by explor202** [comment] 2024-11-20 22:34
@MrAlex94  is this issue unique to Linux? I have run into a similar issue where I can't upgrade from 5.1.12 to 6.5.1 as noted [here](https://github.com/BrowserWorks/Waterfox/issues/3628).

**Comment by Mycohl** [comment] 2024-11-21 18:24
> Also no one has flagged this as abuse, a very odd comment.

You flagged my other comment as abuse before it was deleted, so you're a liar as well as a clown.

**Comment by ghost** [comment] 2024-11-26 15:16
I have just run the update from 6.5.1 to 6.5.2 on both my Linux Mint 22 PCs and it failed with the same error as before:

```
richardt@Avalon:~ $ waterfox
[fluent-dom] An element named "helpus-donateLink" wasn't found in the source.
richardt@Avalon:~ $ /opt/waterfox/updater: error while loading shared libraries: libmozsqlite3.so: cannot open shared object file: No such file or directory
^C
richardt@Avalon:~ $ 
```

@MrAlex94 - does the bug fix that you have included affect the upgrade from 6.5.1, or only upgrades from 6.5.2 ?

**Comment by MrAlex94** [comment] 2024-11-26 15:23
Okay, `6.5.2` is now out and I've _added_ `$ORIGIN`to the `RPATH`. On the systems I've had issues with, this seems to be resolved.

Weirdly enough, on a fresh VM for Ubuntu 22.04 and 24.04, I couldn't repro the issue, but on Debian 12 I could. No idea what the root cause actually is without investing more time.

Please re-open if this occurs.

@explor202, unrelated issue.

**Closed as completed by MrAlex94** 2024-11-26 15:23 UTC
Labels: bug

**Comment by Ketrel** [comment] 2024-11-26 15:47
I'd compare the system version of that library on the two VMs. I'd bet the ubuntu one likely matches.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ibeladi-mrsool** [comment] 2024-11-26 16:03
I think it is still exist in 6.5.2, as it failed for me when updating from 6.5.0 to 6.5.2

To reduce the number of messages ongoing, please:
Thumb up this message if it exists for you too
Thumb down if it does not

**Comment by PixelOfDeath** [comment] 2024-11-26 17:32
Hat the issue from 6.5.0 to 6.5.1 and now again from 6.5.1 to 6.5.2. On Xubuntu 23.10.
Unpacking the tar.bz2 and it works just fine.

**Comment by MrAlex94** [comment] 2024-11-26 18:06
Just a note, the existing `updater` binary has the issue; the binary provided in `6.5.2` has fixed the issue, but if you're on `6.5.0` or `6.5.1`, the update will of course still fail. Updates starting from `6.5.2` onward should no longer fail.

**Comment by gc-user** [comment] 2024-11-27 09:42
Can confirm @MrAlex94 

Had this issue when updating from 6.5.0 to 6.5.1 and now from 6.5.1 to 6.5.2.
So I checked this thread again and saw your post (the one just above mine). Downloaded the archive manually, dropped just the `updater` file into the waterfox directory and executed `updater`. Then the updated went through fine and waterfox started fine with 6.5.2 update applied.

Thanks for the fix!

**Comment by Megalomaniak** [comment] 2024-12-12 12:50
```
>>> waterfox-g4
[27812, Main Thread] WARNING: Locale not supported by C library.
        Using the fallback 'C' locale.: 'glib warning', file /home/runner/work/Waterfox/Waterfox/toolkit/xre/nsSigHandlers.cpp:187

(waterfox:27812): Gtk-WARNING **: 14:20:46.840: Locale not supported by C library.
        Using the fallback 'C' locale.
/opt/waterfox-g4/updater: error while loading shared libraries: libmozsqlite3.so: cannot open shared object file: No such file or directory
>>> echo $LD_LIBRARY_PATH 
/usr/local/lib
>>> LD_LIBRARY_PATH=/opt/waterfox-g4/                                                                                                                                                                  
>>> export LD_LIBRARY_PATH                                                                                                                                                                            
>>> sudo ldconfig
[sudo] password for user: 

>>> echo $LD_LIBRARY_PATH                                                                                                                                                                             
/opt/waterfox-g4/
>>> waterfox-g4
[28760, Main Thread] WARNING: Locale not supported by C library.
        Using the fallback 'C' locale.: 'glib warning', file /home/runner/work/Waterfox/Waterfox/toolkit/xre/nsSigHandlers.cpp:187

(waterfox:28760): Gtk-WARNING **: 14:22:09.932: Locale not supported by C library.
        Using the fallback 'C' locale.

(process:28760): Gtk-WARNING **: 14:22:10.025: Locale not supported by C library.
        Using the fallback 'C' locale.
[28760, Main Thread] WARNING: Locale not supported by C library.
        Using the fallback 'C' locale.: 'glib warning', file /home/runner/work/Waterfox/Waterfox/toolkit/xre/nsSigHandlers.cpp:187

(waterfox:28760): Gtk-WARNING **: 14:22:17.332: Locale not supported by C library.
        Using the fallback 'C' locale.
[Parent 28760, Main Thread] WARNING: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed: 'glib warning', file /home/runner/work/Waterfox/Waterfox/toolkit/xre/nsSigHandlers.cpp:187

(waterfox:28760): Gdk-CRITICAL **: 14:22:20.319: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
[Parent 28760, Main Thread] WARNING: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed: 'glib warning', file /home/runner/work/Waterfox/Waterfox/toolkit/xre/nsSigHandlers.cpp:187

(waterfox:28760): Gdk-CRITICAL **: 14:22:21.323: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
[Parent 28760, Main Thread] WARNING: Unable to register object on bus: An object is already exported for the interface com.canonical.dbusmenu at /com/canonical/menu/0: 'glib warning', file /home/runner/work/Waterfox/Waterfox/toolkit/xre/nsSigHandlers.cpp:187

(waterfox:28760): LIBDBUSMENU-GLIB-WARNING **: 14:22:21.324: Unable to register object on bus: An object is already exported for the interface com.canonical.dbusmenu at /com/canonical/menu/0
```

Hint, by the end there it worked again.

**Comment by eric7dev** [comment] 2024-12-15 07:39
This has happened twice since I've started trying out waterfox a few months back, seems the issue keeps happening with each update. This firefox fork is too unstable, better stick to the official vanilla Firefox. Does not worth the troubleshooting time.

**Comment by Megalomaniak** [comment] 2024-12-15 13:38
> This firefox fork is too unstable, better stick to the official vanilla Firefox. Does not worth the troubleshooting time.

Consider LibreWolf instead.
