### ISSUE TITLE
Please make a 'Waterfox Current' portable.. I need it..

### ISSUE THREAD

**Issue by hosadokha** [MrAlex94/Waterfox#1518] opened 2020-04-02 03:27 UTC
Waterfox Current would be my main browser if it was portable.. I only use portable browsers because of my life.. That the only thing I wanted to say.. 
oh, and it has to be **TRULY** portable

**Comment by grahamperrin** [comment] 2020-04-02 21:06
Duplicate of #1270

Please close this and subscribe to the earlier issue. Thank you.

**Closed as completed** 2020-04-02 23:35 UTC

**Comment by jrappen** [comment] 2020-04-09 00:04
duplicate of #943
