### ISSUE TITLE
Bookmark Toolbar right-click menu problem

### ISSUE THREAD

**Issue by GodOdmin** [MrAlex94/Waterfox#2470] opened 2021-12-06 09:15 UTC
### What happened?

 Waterfox G4.0.3.1 on Win10 2004. Noticed that right-click menu on bookmarks in Bookmark Toolbar has most of the entries grayed out (Open, Open in new tab, etc) Only "Open in private tab" and some Bookmark Toolbar settings are available. Right-click menu on same bookmark, but from from bookmark sidebar (CTRL+B) works fine. I've created a new profile in same custom folder as main one. First start of new profile, added some new bookmarks to the toolbar. Right-click menu works fine. Second start - same problem appears.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by Tafitson** [comment] 2021-12-06 10:37
I have the same Problem.
Seems to work fine in current Firefox (94.0.2).

**Comment by Tafitson** [comment] 2021-12-06 10:41
Just seen that this is a duplicate of #2450 though

**Comment by GodOdmin** [comment] 2021-12-06 10:52
Duplicate of https://github.com/WaterfoxCo/Waterfox/issues/2450

**Closed as completed** 2021-12-06 10:51 UTC
Labels: bug
