### ISSUE TITLE
Missing UI Elements in titlebar/tabbar on macOS in 2020.01

### ISSUE THREAD

**Issue by jrappen** [MrAlex94/Waterfox#1357] opened 2020-01-13 12:04 UTC
### Description

Waterfox 2020.01 on macOS is missing UI Elements in the titlebar / tabbar.

### Screenshots

<img width="842" alt="image" src="https://user-images.githubusercontent.com/8577450/72254519-91140980-3604-11ea-9c56-26912f39f7c3.png">

### Configuration

```yaml
Waterfox:
  build: 2020.01
  channel: current
    portable: false
  platform: osx x64
    version: macOS Catalina 10.15.2 (19C57)
  hardware: MBP 15" 2018, i9 2.9GHz, 32GB, 1TB, Radeon Pro 560X
```

**Comment by jrappen** [comment] 2020-01-13 12:06
As a test I tried with the all included themes (default, light, dark), same issue with all.

**Comment by hawkeye116477** [comment] 2020-01-13 20:24
Seems that's duplicate of https://github.com/MrAlex94/Waterfox/issues/1350.

**Comment by MrAlex94** [comment] 2020-01-22 20:28
@hawkeye116477 

So the changes to [this file](https://github.com/MrAlex94/Waterfox/pull/1289/files?file-filters%5B%5D=.css&file-filters%5B%5D=.xul#diff-319681664db9734fb1a797cfbcabbc94) are the reason for the titlebar buttons to not show on macOS. The position for them is all messed up though when adding macOS specific if guards. Which bit effects the distance to the tab?

![screenshot](https://i.snipboard.io/bMJZQT.jpg)

**Comment by hawkeye116477** [comment] 2020-01-23 14:44
I'm not sure what you mean by `bit`. You'll need to set padding-left for element with id `TabsToolbar`. 
Anyway, I see now that I bit much complicated that and can be made simpler, so you won't need to add padding or set distance from top. It's almost ready, so I'll make PR with fixes later.

**Comment by PK2702** [comment] 2020-02-09 18:26
#1393

**Closed as completed** 2020-02-16 11:26 UTC
Labels: bug
