### ISSUE TITLE
Compact shown as Not Supported in Density menu, but Compact density does work

### ISSUE THREAD

**Issue by mbrazil** [MrAlex94/Waterfox#2583] opened 2022-02-18 00:58 UTC
### What happened?

The release notice for G.4.0.7 says, "The User Interface is now no longer compact by default. You can change this by going ☰ (Menu) → More Tools → Customise Toolbar. In the bottom left corner is the menu option for Density." In the Density menu, it says, "Compact (Not Supported)". However, when I hover the mouse cursor over each of the options in the menu (Compact, Normal, and Touch), the height of the toolbars and the spacing between the toolbar icons does change accordingly, and Compact mode is functional when selected.

A (possibly) secondary issue is that the Density menu doesn't remain visible the first time I click the Density button after opening Customize toolbar. The menu flashes on and then immediately disappears. The second and subsequent times I click the Density button, the menu behaves normally until the next time I select Customize toolbar. The other menus of the Toolbars and Themes buttons don't exhibit this behavior, and clicking either of them prior to clicking the Density button also prevents the disappearance of the Density menu the first time the Density button is used.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment] 2022-02-22 11:42
This is now fixed in https://github.com/WaterfoxCo/Waterfox/commit/a4251ef0a08f313f18f22904e814aa71cb8f4fb6. Thanks!

**Closed as completed by MrAlex94** 2022-02-22 11:42 UTC
Labels: bug

**Comment by ggdorman** [comment] 2026-03-10 17:14
The issue is still present on v6.6.9.
