### ISSUE TITLE
userChrome broken in G5

### ISSUE THREAD

**Issue by the-r3dacted** [MrAlex94/Waterfox#2780] opened 2022-08-17 17:26 UTC
### What happened?

Because of the modified theme, userChrome.css is kinda broken.

![ScreenShot_20220817122501](https://user-images.githubusercontent.com/77039240/185203560-8b4b18da-9f6f-4a1e-958c-0ee9393a13ef.png)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment] 2022-08-17 18:13
Thanks - will try and detect if a custom userChrome is being set and unregister the default userChromes when that happens.

As a quick workaround, could you try installing a random theme such as: https://addons.mozilla.org/en-US/firefox/addon/pure-neutral/?

**Comment by the-r3dacted** [comment] 2022-08-17 18:19
> As a quick workaround, could you try installing a random theme such as: https://addons.mozilla.org/en-US/firefox/addon/pure-neutral/?

It kinda works but not really, it's still bugged like that.

**Comment by starfan101** [comment] 2022-08-17 19:22
dose anyone have a link too the g5 so i can test it

**Comment by troysjanda** [comment] 2022-08-17 21:20
Should add back the original Firefox default themes. Let the user decide the theme they would like to use.

**Comment by MrAlex94** [comment] 2022-08-18 08:24
> > As a quick workaround, could you try installing a random theme such as: https://addons.mozilla.org/en-US/firefox/addon/pure-neutral/?
> 
> It kinda works but not really, it's still bugged like that.

Hmm, might be something else then. Do your customisations work on ESR102?

**Comment by thunderstone135** [comment] 2022-08-18 08:46
@MrAlex94:
I noticed that you updated Lepton. The reason the theme is no longer working is due to the CSS code being placed in userChrome.css inside omni.ja. The CSS code should be placed in leptonChrome.css and just mentioned in userChrome.css using this line:
```
@import url("css/leptonChrome.css");
```
Additionally, the updated Lepton is now using **[user.js](https://github.com/black7375/Firefox-UI-Fix/blob/master/user.js)**.

**Comment by the-r3dacted** [comment] 2022-08-18 14:36
> > > As a quick workaround, could you try installing a random theme such as: https://addons.mozilla.org/en-US/firefox/addon/pure-neutral/?
> > 
> > 
> > It kinda works but not really, it's still bugged like that.
> 
> Hmm, might be something else then. Do your customisations work on ESR102?

I don't need to test ESR102, they worked fine on Firefox 101, 102, and 103. ESR shouldn't be any different.

**Comment by Keefaetana** [comment] 2022-08-18 15:44
> @MrAlex94: I noticed that you updated Lepton. The reason the theme is no longer working is due to the CSS code being placed in userChrome.css inside omni.ja. The CSS code should be placed in leptonChrome.css and just mentioned in userChrome.css using this line:
> 
> ```
> @import url("css/leptonChrome.css");
> ```
> 
> Additionally, the updated Lepton is now using **[user.js](https://github.com/black7375/Firefox-UI-Fix/blob/master/user.js)**.

Perhaps something about this is why Tab Mix Plus can't do multi-row tabs anymore, too?

**Comment by thunderstone135** [comment] 2022-08-19 07:25
> Perhaps something about this is why Tab Mix Plus can't do multi-row tabs anymore, too?

I'm not sure since I'm not using the Multi-row tabs feature of Tab Mix Plus. You have to ask @onemen or @black7375 about it.

**Comment by black7375** [comment] 2022-08-19 08:09
Is Waterfox G5 using `Lepton v5.0.0` or higher?
All options are activated using [`configs`](https://github.com/black7375/Firefox-UI-Fix/blob/master/user.js), and nothing changes without options.

---

The reason for conflicting with [`TabMixPlus`](https://github.com/onemen/TabMixPlus) is because of `!important` in userChromeCSS.
In userChromeCSS, it does not work without `!important` due to [css loading order](https://github.com/black7375/Firefox-UI-Fix/blob/master/docs/Restrictions.md#css-loading-order).

**Comment by onemen** [comment] 2022-08-19 08:57
Try to change the theme, currently `Tab Mix Plus` multi-row work only with modern theme.

Anyone that is willing to help me make Tab Mix Plus work with all `Waterfox` theme please post a PR [here](https://github.com/onemen/TabMixPlus/pulls)

**Comment by MrAlex94** [comment] 2022-09-05 16:45
I've added a pref, `userChrome.theme.enable`, which can be toggled to `false` to disable the Lepton customisations.

This will be in Beta 2 - so hopefully people can try and see if it stops conflicting with their specific customisations.

**Comment by troysjanda** [comment] 2022-09-05 17:00
Awesome Alex thanks for listening as always. Also for the hard work.

**Comment by thunderstone135** [comment] 2022-09-06 10:11
@MrAlex94
You actually don't need to disable the Lepton theme. You just need to place `userChrome.css` inside the `css` folder, then rename it to `leptonChrome.css`. After that, create another `userChrome.css` file and type `@import url("css/leptonChrome.css");`. For `userContent.css`, just repeat the same steps.

**Comment by thunderstone135** [comment] 2022-09-06 10:18
@MrAlex94
You actually don't need to disable the Lepton theme. You just need to place `userChrome.css` inside the `css` folder, then rename it to `leptonChrome.css`. After that, create a new `userChrome.css` file and type `@import url("css/leptonChrome.css");`, then place it outside the `css` folder. For `userContent.css`, just repeat the same steps.

If you want a much easier step, just download the latest Lepton release **[here](https://github.com/black7375/Firefox-UI-Fix/releases)** and just copy these items:
- css folder (which contains leptonChrome.css and leptonContent.css)
- userChrome.css
- userContent.css
- user.js

P.S. For `user.js`, you just need to copy the prefs and integrate it with Waterfox (at least the default ones, the non-default ones have `//` or `/* */` on them).

**Comment by the-r3dacted** [comment] 2022-09-06 19:25
![ScreenShot_20220906142354](https://user-images.githubusercontent.com/77039240/188721585-13c6d4d4-eeb4-45f2-b7dd-d1608414d80c.png)
Works for me, but I'd like to see others have success before closing.

**Comment by MrAlex94** [comment] 2022-09-16 14:37
@onemen,

We've now reworked the way our custom CSS is loaded in 864a21038e369ce0b3f61ea7a6ae660ee4c5c577.

Some [API notes](https://searchfox.org/mozilla-esr68/source/layout/base/nsIStyleSheetService.idl):

```
   * A user sheet loaded via this API will come before userContent.css and
   * userChrome.css in the cascade (so the rules in it will have lower
   * precedence than rules in those sheets).
```

I'm hoping this means that TabMixPlus will work without having to disable Lepton.

**Closed as completed** 2022-10-05 15:40 UTC
Labels: bug

**Comment by onemen** [comment] 2022-10-05 18:13
@MrAlex94,

So far with G5, [Multi-row tabs does not work properly](https://github.com/onemen/TabMixPlus/issues/168) 

Changing `userChrome.theme.enable` to **false**  seems to fix this issue.

How do i need to load Tab Mix Plus style-sheets in order to avoid this issue. keep in mind that the solution need to be compatible with Firefox.

**Comment by onemen** [comment] 2022-10-05 20:00
@MrAlex94,

The issue is in the file userChrome.css:
```css
/** Tab UI ****************************************************************/
/*= Tab - Connect to window ==============================================*/
@supports -moz-bool-pref("userChrome.tab.connect_to_window") {
...
  #TabsToolbar {
    overflow: hidden;
    /* Prevent toolbar area over */
  }
...
}
```

The rule **overflow: hidden** caused the issue, I can fix it by adding this to `Tab Mix Plus` styles
```css
#TabsToolbar[multibar] {
  overflow: unset !important;
}
```

**Comment by black7375** [comment] 2022-10-06 11:49
Lepton is planning to add feature related to multirow.
- https://github.com/black7375/Firefox-UI-Fix/commits/dev
- https://github.com/black7375/Firefox-UI-Fix/issues/315
