### ISSUE TITLE
Is Waterfox for Android dead?

### ISSUE THREAD

**Issue by androidacy-user** [MrAlex94/Waterfox#1372] opened 2020-01-24 02:08 UTC
I have yet to find a link that works to download it.

I've searched on GitHub - every link listed in issues is 404, whether play store or website.

It's not listed in releases on the website.

Please don't abandon Android. I started using it on windows 10 (waterfox current not classic) and I love it. I'm running an arm64 device as well so 32bit not a problem (pixel 2 xl)

**Comment by androidacy-user** [comment] 2020-01-24 02:10
And last version on apkmirror is almost 2years old

**Comment by Ibuprophen** [comment] 2020-01-24 02:47
The https://github.com/MrAlex94/Waterfox/issues/730 issue is still open that is a duplicate of this issue. 

The https://github.com/MrAlex94/Waterfox/issues/1233#issuecomment-548565554 provides how to be able to view the 32-bit version that is only available as a Beta. The instructions & explanation are in there. 

Good Luck! 


~Ibuprophen

**Comment by androidacy-user** [comment] 2020-01-24 02:48
And as I already said those links are dead and my device is 64bit anyhow

**Comment by androidacy-user** [comment] 2020-01-24 02:52
![Screenshot_20200123-215144](https://user-images.githubusercontent.com/45006100/73041230-a110c200-3e2a-11ea-852f-00bb4efc3c10.png)
After signing up for the beta, still nothing. Searching in play store doesn't help either

**Comment by hawkeye116477** [comment] 2020-01-24 09:35
In short, Google removed it and doesn't want to tell why.

**Comment by androidacy-user** [comment] 2020-01-24 11:54
https://storage-waterfox.netdna-ssl.com/releases/android is 403 not 404 tho 🤔

**Comment by grahamperrin** [comment] 2020-02-18 01:18
▶ [I can't see Waterfox in Android Playstore · Issue #1085 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/1085)

**Comment by MrAlex94** [comment] 2020-11-16 10:21
https://github.com/MrAlex94/Waterfox/issues/730

**Closed as completed by MrAlex94** 2020-11-16 10:21 UTC
