### ISSUE TITLE
G6.0.5: Tab crashes on certain html files

### ISSUE THREAD

**Issue by Mikhail-M12** [MrAlex94/Waterfox#3254] opened 2023-10-30 19:12 UTC
### What happened?

G6.0.5 can't open certain html files (created by SingleFile addon). Example: 
[Tier List Maker for Everything - TierMaker (2023-10-28 9_41_23 PM).zip](https://github.com/WaterfoxCo/Waterfox/files/13209034/Tier.List.Maker.for.Everything.-.TierMaker.2023-10-28.9_41_23.PM.zip)
Tab crashes.

Firefox 115.4.0 opens this file normally.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by robbely** [comment] 2023-10-30 20:03
I'm having the same issue with the similar addon SingleFileZ. Here is what I posted on the addon's github:

> 
> If I use SingleFilesZ to save the page from "https://store.steampowered.com/app/1722660/Hamster_on_Rails/" as an example with large gifs, the file appears to save correctly. However if I reload into Waterfox (latest: G6.0.5 based on latest Firefox ESR) I get the Gah Tab Crashed error. (The saved page loads successfully however in the equivalent Firefox ESR release).
> 
> I've tried with clean install of Waterfox and not changing any SingleFileZ settings.
> 
> If I open the saved page in winrar and delete the 3 large gifs from the images folder the page will then load successfully in Waterfox.

I have tested the saved file on a number of browsers now (including TorBrowser which is also ESR based) and only Waterfox is crashing with the saved file. Does anyone know if there is an about:config setting (or anything else that might be set differently to Waterfox than other Firefox ESR browsers) that might allow more memory in a tab before the tab gives up and crashes?

**Comment by cosmoderp** [comment] 2023-11-02 20:22
Was looking around and this bug report seems about right.  Although mine is of yet another similar plugin "Save Page WE" I in my case traced it down to a single line large embedded animated GIF file `data:image/gif` normally a standalone 16mb GIF.  When that large single line code is removed from from the html the page loads fine.  This same html file loads fine without modification in several other browsers. Also to note that the crash is instant, at least in my case it does not seem to try and load anything.

**Comment by robbely** [comment] 2023-11-02 21:30
> This same html file loads fine without modification in several other browsers.

I haven't been able to reproduce the issue in any other browser than Waterfox, so it is definitely something specific to Waterfox.

Also I tried saving a YouTube page normally (not using an addon) and the result when loaded also gives the Gah error (again only in Waterfox).

**Comment by cosmoderp** [comment] 2023-11-02 23:42
So after adding SinglefileZ to test it as well I saw its output is a completely different type of file from "save page we" but it produces the same crash.  Saving as a normal complete page with a folder structure does not cause this crash. 

Playing around with inspecting and editing the HTML on the sites I can get the crash every time I simply add the link for the large file GIF.  I found other large GIF images to test with and got the same results.

Also tried the youtube video page and you are right.  It also only crashed on Waterfox but it would be hard to tell if the two are breaking for the same reason cause there are times when both extensions outputs will not crash on waterfox.

**Comment by robbely** [comment] 2023-11-03 00:16
>  hard to tell if the two are breaking for the same reason cause there are times when both extensions outputs will not crash on waterfox.

It is true the reasons may be different (for instance saving a youtube page doesn't seem to generate any large files like the addons do), but both crashes are Waterfox-only ones (I can't reproduce the crashes in other firefox or chrome flavours), so there is either one or two things broken in Waterfox.

**Comment by scherno2000** [comment] 2023-11-27 11:59
I created a test html file as simple as possible. 
```
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8"/>
    <title>MyText</title>
  </head>
  <body>
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx<br/>
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx<br/>
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx<br/>
... and so on (approx 41100+ lines) until the file gets bigger than 4194304 bytes 
 </body>
</html>
```
For me it crashes on files > 4194304 bytes which is 2^22, that hints to me that is some overflow.

**Comment by MaskedMudpuppy** [comment] 2024-01-15 01:16
I have the same issue with large offline twine html games but only with G6 versions of  Waterfox. The older G5 versions of Waterfox works fine as well as Firefox and Chrome...

**Comment by robbely** [comment] 2024-03-22 16:37
Seems fixed in G6.0.10

**Closed as completed** 2024-03-22 19:15 UTC
Labels: bug
