### ISSUE TITLE
[Classic] 2021.07 not working on https://gitlab.com/ and others due to "customElements" not being found

### ISSUE THREAD

**Issue by rorya** [MrAlex94/Waterfox#2175] opened 2021-07-20 15:24 UTC
### What happened?

latest version of Classic is not working on gitlab.com. Console shows "ReferenceError: customElements is not defined"

Even trying to use this very form (issues submission) on this site (github.com) falis, for the same reason.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

macOS

### Relevant log output

```shell
ReferenceError: customElements is not defined[Learn More]  gl_emoji.js:78:7
	F2LA gl_emoji.js:78:7
	t bootstrap:84:3
	HVBj/< https://gitlab.com/assets/webpack/main.215af7d8.chunk.js:44:82815
	HVBj https://gitlab.com/assets/webpack/main.215af7d8.chunk.js:44:82734
	t bootstrap:84:3
	[177] https://gitlab.com/assets/webpack/pages.projects.merge_requests.show.c627df31.chunk.js:1:71550
	t bootstrap:84:3
	c bootstrap:45:14
	a bootstrap:32:10
	<anonymous> https://gitlab.com/assets/webpack/pages.projects.merge_requests.show.c627df31.chunk.js:1:2
```

**Comment by hawkeye116477** [comment] 2021-07-20 17:03
It's duplicate of https://github.com/MrAlex94/Waterfox/issues/2132. Please search issues before posting another one :smile:.

**Comment by rorya** [comment] 2021-07-20 18:07
ah, so I guess, as I read it, there are no plans to support Web Components.. so I guess that means it's unlikely to ever be resolved on Classics.. Thanks for the prompt response.

**Closed as completed** 2021-07-20 18:07 UTC
Labels: bug

**Comment by reallyuniquename** [comment] 2021-07-20 20:27
@rorya https://github.com/JustOff/github-wc-polyfill/issues/26#issuecomment-883528863
