### ISSUE TITLE
White Bar at Bottom of Fullscreen YouTube Video on Waterfox G4 0.3.1

### ISSUE THREAD

**Issue by ItsAvrilNotAveral** [MrAlex94/Waterfox#2454] opened 2021-11-25 23:12 UTC
### What happened?

When in a fullscreen video, there is a small white bar present at the bottom of the screen. This bug does not occur on regular firefox.
I have attached an image of the issue to this bug report.

![WaterfoxBug](https://user-images.githubusercontent.com/95056340/143506819-f89b82ff-5017-4fd5-8631-1cb1cad85ad3.png)
.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by this-is-your-do** [comment] 2021-12-03 10:52
I've noticed this as well - and it's not specific to Youtube, it happens whenever you enter fullscreen mode (though it can be hard to notice on white/light-gray websites).

**Comment by this-is-your-do** [comment] 2021-12-03 14:43
(While this line is usually hardly visible, when it is visible (e.g. in screens or videos where most of the bottom area is black), it's highly bothersome - a fix would be appreciated)

**Comment by luzrain** [comment] 2021-12-04 12:03
I have the same issue.

**Comment by adamp01** [comment] 2021-12-08 16:10
@AW2305 @this-is-your-do @luzrain 
- Would you be able to let me know what themes you are using please? 
- Is this limited to one theme are across all themes? 
- Are you all on Windows or is this noticeable across multiple platforms?
Thanks

**Comment by luzrain** [comment] 2021-12-08 16:20
Light theme. On the dark theme I don't see that line.
I tested it on Windows 7 and Windows 10.

**Comment by TankedThomas** [comment] 2021-12-10 12:25
Same issue here. I can reproduce it on both Windows (10 21H2) and macOS (Monterey). I think I had it on Linux too but not sure and can't check right this moment.

I'm using the Waterfox Lepton theme and syncing between all three operating systems (plus Fennec F-Droid on Android). 
If it matters, I'm also using the Improve YouTube extension (turning it off doesn't seem to make a difference, however, other than fixing a whole ton of _unrelated_ issues that have popped up today, probably thanks to said extension).

I tried all the default themes and they all display this behaviour. 
There are black bars for the themes that pad with black instead of white. 

It seems like a padding issue, because if I made the background of YouTube/Odysee/whatever white or transparent instead of black, you can see white bars on the sides too. I don't see them at the top usually but I did at one stage.

**Comment by adamp01** [comment] 2021-12-10 12:57
Thanks for the additional comments here. I've taken a look and can confirm that the white/black bar is there at all times irrespective of fullscreen etc. I imagine I'll have a fix for this in the next version.

**Comment by adamp01** [comment] 2021-12-10 13:19
Here is a temporary fix and a helpful testing opportunity - if any of you could do this, use the browser and report back that would be helpful.
1. Open the browser toolbox (Ctrl+shift+alt+I - I think), or Tools -> Browser Tools -> Browser Toolbox; there is a prompt you need to accept for Browser <> Toolbox messaging 
2. Scroll to the main browser content and add padding-top: 1px; to the element rule as below:
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/47503375/145579987-b8f1e5f6-2c3c-4118-9739-24e33c9330c3.png">
Let me know if that causes any other issues and if not I'll commit to the browser css.

Thanks!

**Comment by TankedThomas** [comment] 2021-12-10 14:29
I just gave it a try but, at least for me, it's shifting the white bar on the bottom to the white bar on the top (or, probably more accurately, it seems the full screen... isn't completely full). I played around with other padding arrangements but nothing seems to work. I guess I was wrong about it being a padding issue, at least specifically relating to CSS.

Interestingly, if I try adding to the bottom padding and/or margin, it doesn't move the contents up, but adding more to the top padding/margin will continue adding white space at the top (and yes, I tried both margin and padding in the CSS). Also, I found that the specific point at which this will happen is a top padding of 0.5px. At 0.499px or less, it stays unchanged from the current default (white bar on bottom).

Something else interesting I noticed, which I noticed previously but didn't catch earlier today, is that I'm getting the bars down the sides tapering off towards the bottom two corners. 
For whatever reason, my Stylus theme that makes the YouTube cinematic background transparent instead of black doesn't display the white bars down the sides, but the Improve YouTube extension doing the same thing _does_ show them, and since I turned the extension off because it was causing other issues, I didn't catch this until I checked Odysee, on which I also use a Stylus theme to make the background transparent.

Hopefully you can see the taper clearly enough here:
![image](https://user-images.githubusercontent.com/8655939/145589793-4b34c006-9aed-4553-8c25-fbc0fc206f22.png)

Just like with YouTube, I'm getting no bar on the top until I add padding to the top on Odysee, which takes away the white bar on the bottom. So perhaps this is to do with scaling instead, or maybe a combination. I'm not sure. I tried adjusting the scale in CSS but it didn't help much, and in conjunction with padding, it helped a little more, but it's still not quite right.

I believe it started happening with G4.0.2, because I recall hoping for an update to fix it, but G4.0.3 didn't, and now G4.0.4 is out, to which I noted it still wasn't fixed. That might at least help to narrow down where/when the problem started happening, because I'm pretty sure G4.0.1 didn't have this issue.

**Comment by adamp01** [comment] 2021-12-15 12:14
I've found the issue and will be doing a PR so this is fixed in the next release.

**Closed as completed** 2021-12-15 13:42 UTC
Labels: bug
