### ISSUE TITLE
Bug: can not get it to work  version `GLIBC_2.30' not found

### ISSUE THREAD

**Issue by rubyFeedback** [MrAlex94/Waterfox#2270] opened 2021-09-26 21:35 UTC
/Depot/jjjj/waterfox/./waterfox
    XPCOMGlueLoad error for file /Depot/jjjj/waterfox/libnspr4.so:
    /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /Depot/jjjj/waterfox/libnspr4.so)
    Couldn't load XPCOM.
    /Depot/jjjj/waterfox/glibc?
    ldd (Debian GLIBC 2.28-10) 2.28
    Copyright (C) 2018 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    Written by Roland McGrath and Ulrich Drepper.

PS: I first tried to file it under bug, but palemoon does not work with github; the drop down box I can not select.

Also it is weird that the bug report template requires us to check whether we tested this on firefox.

Is it forbidden to use waterfox without firefox? If not then the template should not ask for firefox;
I last used firefox in 2017 or so, excluding a windows environment on an elderly relative.

**Comment by hawkeye116477** [comment] 2021-09-27 08:20
It looks like duplicate of https://github.com/WaterfoxCo/Waterfox/issues/2259

**Closed as completed** 2021-10-20 11:57 UTC
Labels: enhancement
