### ISSUE TITLE
kaggle.com doesn't load

### ISSUE THREAD

**Issue by OzoneReloaded** [MrAlex94/Waterfox#1833] opened 2020-11-22 14:56 UTC
**Describe the bug**
https://www.kaggle.com/ doesn't work properly. Page resets after a few seconds of loading.

**To Reproduce**
1. Go to 'https://www.kaggle.com/'

**My configuration**
 - OS: Windows 10
 - Version: Waterfox Current 2020.10 (64 bit)

**Comment by OzoneReloaded** [comment] 2020-11-22 18:41
Could someone confirm please?

**Comment by hawkeye116477** [comment] 2020-11-22 18:52
I can confirm, but Waterfox Current is EOL, so this won't be fixed. You will need to migrate to Waterfox G3.

However that bug is also on Waterfox Classic.

**Comment by OzoneReloaded** [comment] 2020-11-22 19:09
> 
> 
> I can confirm, but Waterfox Current is EOL, so this won't be fixed. You will need to migrate to Waterfox G3.
> 
> However that bug is also on Waterfox Classic.

I didn't know about existence of G3 at all and thought Current is the main branch. Thank you!

**Comment by tcreek** [comment] 2020-12-01 20:22
I can confirm with Waterfox Classic on Linux and Windows 10

**Comment by hawkeye116477** [comment] 2020-12-05 17:43
Looks like, this should be implemented => https://bugzilla.mozilla.org/show_bug.cgi?id=1374612 to fix that.

**Closed as completed** 2021-05-27 14:03 UTC
Labels: bug

**Comment by tcreek** [comment] 2021-05-27 14:14
Kaggle seems to display now in 2021.04.02
