### ISSUE TITLE
Tabbing from Address Bar does not go to Search Bar

### ISSUE THREAD

**Issue by GuestJim** [MrAlex94/Waterfox#1870] opened 2020-12-17 14:42 UTC
The behavior when pressing Tab from the Address Bar has changed in G3.0.2 from Current 2020.10. Previously (2020.10) doing so brought focus from the Address Bar to the Search Bar. Now (G3.0.2) brings focus from the Address Bar to the first extension icon. 
If you continue tabbing from the Address Bar, focus never goes to the Search Bar. If you Shift + Tab from the first extension icon, however, the Search Bar is focused.
My apologies if this has been reported elsewhere and I did not find it.

**Repro Steps:**
1. Focus Address Bar (mouse click, F6, etc.)
2. Press Tab
3. Note what is now focused

**Expected Behavior:**
Pressing Tab from Address Bar focuses Search Bar

**Screenshots**
![WF G3 0 2 Tabbing](https://user-images.githubusercontent.com/30958420/102501218-2efd2900-404b-11eb-9cff-c6b49d84b142.png)

**My configuration** 
 - Device: PC
 - OS: Windows 10 (2004)
 - Version: Waterfox G3.0.2

**Comment by anonvoy** [comment] 2020-12-20 23:17
Can confirm with Waterfox G3.0.2 on OpenSUSE Linux Leap 15.1. Same behavior.

**Comment by anonvoy** [comment] 2021-02-02 19:03
That behavior is still there in Waterfox G3.1.0 (Linux tarball version from https://www.waterfox.net/download/).

**Comment by hedgehog1029** [comment] 2021-03-13 03:47
this has ruined my muscle memory lmao

**Comment by anonvoy** [comment] 2021-03-24 18:41
Still not resolved in Waterfox G3.2.0.

**Comment by prg318** [comment] 2021-05-27 16:34
Did this get resolved?  Why was this closed

**Comment by MrAlex94** [comment] 2021-05-27 16:39
Current -> G3 was ESR 68 -> ESR 78. Does ESR 78 exhibit the same behaviour?

**Comment by prg318** [comment] 2021-05-27 16:44
I can still reproduce this on Waterfox G3.2.1 (64-bit) based on Gecko 78.10.0

**Comment by MrAlex94** [comment] 2021-05-27 17:27
Right, but I need to know if it's reproducible on Firefox ESR.

**Comment by prg318** [comment] 2021-05-27 18:43
This issue is exclusive to waterfox.  Firefox esr never had this issue and still doesn't with 78.10.0esr

I would recommend trying it and seeing for yourself; it's trivial to reproduce

**Comment by Bielecki** [comment] 2021-07-07 08:30
Bumping as it still exist on G3.2.3 (64-bit) (Gecko 78.12.0) (both Linux and Windows) and it's irritating for more than a half year now. Seems exclusive to Waterfox, as Firefox doesn't have this issue.

**Comment by prg318** [comment] 2021-07-07 21:43
If the primary waterfox developer can't even test Firefox ESR for himself, I wouldn't hold your breath that this will get fixed.  I've switched to Librewolf and couldn't be happier https://librewolf-community.gitlab.io/

**Comment by anonvoy** [comment] 2021-07-07 22:11
It's not a solution, but I'm using a kind of workaround: Drag one (or more) of the extension icons between the Address Bar and the Search Bar. That way, pressing Tab once brings you to the first extension icon, pressing it a second time brings you to the Search Bar. It's not ideal, but it's better than having to press Tab and then Shift+Tab.

**Comment by Bielecki** [comment] 2021-07-09 09:31
Another workaround that works for me (on Windows only unfortunately) is to press Ctrl+E and it takes you directly to search bar. I got so used to that so I forgot about this bug, but switching to Waterfox on Linux (where this shortcut doesn't work) reminded me.

**Comment by MrAlex94** [comment] 2021-10-26 09:38
This is now working in G4 as expected. When opening a new tab address bar is focused and pressing tab switches to the search bar. The moment the address bar is interacted with, the tab bar starts scrolling through the address bar options - same behaviour as Firefox.

**Closed as completed by MrAlex94** 2021-10-26 09:38 UTC
Labels: bug
