### ISSUE TITLE
Waterfox 4.3.0.1 -  Right-click on Bookmarks toolbar has many options disabled

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2450] opened 2021-11-24 16:26 UTC
### What happened?

For Adam - 4.3.0.1 has introduced a bug on the right-click on the Bookmarks Toolbar.  Options are disabled that should not be disabled :+1: 

![image](https://user-images.githubusercontent.com/89191739/143276785-3d2a980c-c4ee-443a-be84-21e35de19625.png)

O.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Elsewhereman** [comment] 2021-11-25 09:30
Came here to report the same. Options are there in Troubleshoot Mode, but not in normal mode, even with all extensions disabled. Waterfox 4.0.3.1, Windows 10 Version 21H1 x64.

**Comment by MrAlex94** [comment] 2021-11-25 13:01
Temporary fix appears to be to disable then re-enable the bookmarks toolbar.

**Comment by Elsewhereman** [comment] 2021-11-25 13:11
Thanks Alex! WFM.

**Comment by johnkosm** [comment] 2021-11-25 15:06
Close Waterfox, reOpen Waterfox, and the issue is there again ...

**Comment by ZTrainor** [comment] 2021-11-25 22:01
Same issue.  Thank you very much MrAlex94!

**Comment by Avrution** [comment] 2021-12-05 19:40
Glad it wasn't just me

**Comment by GodOdmin** [comment] 2021-12-06 10:53
I have same issue

**Comment by bigboy65** [comment] 2021-12-07 10:48
There is a work around, in the toolbar dropdown , under bookmarks toolbar select never show, then restart Waterfox and select always show. Then it works until exit Waterfox then you have to do the same thing again. Hopefully it will be fixed in the next update

**Comment by adamp01** [comment] 2021-12-08 16:25
@Objectivite - this should now be resolved in G4.0.4 (getting released today). I'll close this off once the release is out.

**Comment by ZTrainor** [comment] 2021-12-08 16:39
Thank you very much Adamp01!

**Comment by Objectivite** [comment] 2021-12-08 18:26
Thank you Very Much Adamp01.

O.

**Closed as completed** 2021-12-09 14:37 UTC
Labels: bug
