### ISSUE TITLE
Waterfox G4 does not retain anything from G3 when installed over the top

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2324] opened 2021-10-19 19:16 UTC
### What happened?

This is probably the biggest bug of them all.

Upgrading G4 over the top of G3 results in nothing being kept from G3, so all the settings have to be re-done, all the bookmarks re-imported from backups, themes re-installed, extensions re-installed.

**Not good !**

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment] 2021-10-19 20:00
Hi,

Where was the location previously and the location it was installed on?

If you go to `about:profiles` is the old profile listed there?

What version did you upgrade from?

**Comment by Objectivite** [comment] 2021-10-19 20:09
> 
> 
> Hi,
> 
> Where was the location previously and the location it was installed on?
> 
> If you go to `about:profiles` is the old profile listed there?
> 
> What version did you upgrade from?

---------------------------------------------

Hi Alex,

I upgraded from  **Waterfox G3 v3.2.6**.

I downloaded G4 when it was made available through the download button on your website (it was called G4.0.0b3 - 5 minutes later it was just called G4.0.0).

I installed over the top of G3 which I had verified to be in  **C:\Program Files\Waterfox Current**  using  **"Help \ Troubleshooting Information"**

The problem, as I tracked it, is that in  **C:\Users\<User>\AppData\Roaming**  it created a  Waterfox Limited  folder and installed its settings in a Profile folder in there rather than into the existing Waterfox\<profile>  folder.

**Comment by MrAlex94** [comment] 2021-10-19 21:12
Thanks - that's actually really useful to know! Will see if I can fix that ASAP.

**Comment by MrAlex94** [comment] 2021-10-19 21:32
https://github.com/WaterfoxCo/Waterfox/commit/25c98a6caab83934c8eb2a3ee57b3b7e58f650ca should fix the issue. Just pushing a build out now to test and release.

**Comment by Objectivite** [comment] 2021-10-19 22:05
> 
> 
> [6d889b7](https://github.com/WaterfoxCo/Waterfox/commit/6d889b755eadc42107486f74127094c2784c164a) should fix the issue. Just pushing a build out now to test and release.

Glad it helped - I have 4 or 5 PCs in our office that I can connect to to test when it's ready.

O.

**Comment by MrAlex94** [comment] 2021-10-19 23:56
https://cdn.waterfox.net/releases/win64/installer/Waterfox%20G4.0.0.1%20Setup.exe

@Objectivite Should fix the issue :-) please test and let me know 👍

**Comment by Objectivite** [comment] 2021-10-20 07:51
> 
> 
> https://cdn.waterfox.net/releases/win64/installer/Waterfox%20G4.0.0.1%20Setup.exe
> 
> @Objectivite Should fix the issue :-) please test and let me know +1

Hi Alex,

Right - I have just tested this on one of our office PCs and I have some good news and some bad news.

**The Good News**

G4 v4.0.0.1  now keeps  **Themes,  Extensions, and Bookmarks**  and it also keeps the  **Zoom Control and Full Page Control**  on the Status Bar.

**The Bad News**

a)  All cookies are lost.

b)  All passwords are lost

c)  Despite keeping my previous settings for the Tab Bar as  **Top below address Bar**, it went and put the Tab Bar  **at the bottom OVER THE TOP of the Status Bar**.  Basically, immediately after installation everything seemingly looks fine.  Then on clicking on one of the bookmarks, the Tab Bar appears at the bottom overlaying the Status Bar.  Changing the Tab Bar Position in Settings has no effect whatsoever.  So, all considered, that Tab Bar bug makes 4.0.0.1 unusable for anyone who likes their tabs in the upper part of the screen.

Hope this helps.

O.

**Comment by UInt2048** [comment] 2021-10-20 10:26
I just installed G4.0.0.1 and confirm the issue @Objectivite is experiencing.

However, I'd like to clarify that for me, **saved** passwords are not lost, but all sites are logged out.

**Comment by MrAlex94** [comment] 2021-10-20 11:48
@Objectivite, we've done some tests and can't reproduce the passwords not being picked up.

@UInt2048 - sometimes this happens during large upgrades - haven't found a good way to prevent this unfortunately. 

Seems things are back to normal, will close this.

**Closed as completed by MrAlex94** 2021-10-20 11:48 UTC
Labels: bug

**Comment by SaltfishAmi** [comment] 2021-10-20 15:43
> saved passwords are not lost, but all sites are logged out.

> [@]UInt2048 - sometimes this happens during large upgrades - haven't found a good way to prevent this unfortunately.

@MrAlex94  So it is normal behavior to lose cookies upon major update? I can't imagine having to log back in and tweak the settings for each and every site I use.

Seriously, do we even know the reason why this happens?

I've installed back G3.2.6 to make a reply on GitHub, or otherwise it requires me to drag out my backup hard drive to look for some 2-factor auth credentials.

**Comment by MrAlex94** [comment] 2021-10-20 15:50
@SaltfishAmi - unfortunately not. Seems to happen between ESR changes. I can't imagine anything changing regarding format of cookie storage, but might be something to do with it.

**Comment by SaltfishAmi** [comment] 2021-10-21 10:58
> unfortunately not. Seems to happen between ESR changes. I can't imagine anything changing regarding format of cookie storage, but might be something to do with it.

One thing is that after updating to G4, in the settings page I still saw my ~600m of site data and cookies, and in the details dialog the exact number of cookies of each site **did** appear; they were just not working.

**Comment by MrAlex94** [comment] 2021-10-25 14:06
> > unfortunately not. Seems to happen between ESR changes. I can't imagine anything changing regarding format of cookie storage, but might be something to do with it.
> 
> One thing is that after updating to G4, in the settings page I still saw my ~600m of site data and cookies, and in the details dialog the exact number of cookies of each site **did** appear; they were just not working.

This might have been fixed in G4.0.1 for you?

**Comment by SaltfishAmi** [comment] 2021-10-25 15:12
> This might have been fixed in G4.0.1 for you?

Oh, I didn't notice a new release. I'll try it out, thanks a lot!

Edit: Confirmed fixed in G4.0.1!

**Comment by Shitennouji** [comment] 2021-10-25 23:33
>  unfortunately not. Seems to happen between ESR changes. I can't imagine anything changing regarding format of cookie storage, but might be something to do with it.

It feels like a quibble, as if you are shifting the blame.
I am a long-time regular user of Firefox ESR and have never experienced such a case.
This problem occurred with the upgrade from Waterfox G3 to G4 and is specific to the "Waterfox Generation Release" program.
I feel that there is inappropriate program code in Waterfox G4.

This issue seems to have been resolved with "fixed in G4.0.1", but I felt that we should seriously check our own programs for problems instead of shifting the blame to upstream.

**Comment by UInt2048** [comment] 2021-10-25 23:46
@Shitennouji True. However, I believe it's a moot point, since Waterfox plans to track the central branch going forward: https://www.waterfox.net/blog/waterfox-4th-gen
