### ISSUE TITLE
bug: https://storage-waterfox.netdna-ssl.com/releases/win64/portable/WaterfoxPortable_2020.01_English.paf.exe  gives 404

### ISSUE THREAD

**Issue by Huge** [MrAlex94/Waterfox#1364] opened 2020-01-16 16:52 UTC
The current link for downloading the portable classic version seems broken./

**Comment by reallyuniquename** [comment] 2020-01-17 14:38
Dupe of #1358

**Closed as completed** 2020-02-13 18:25 UTC
Labels: bug
