### ISSUE TITLE
[webcompat] www.canva.com - Waterfox is an unsupported browser

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2643] opened 2022-04-04 08:21 UTC
### What happened?

URL: https://www.canva.com/

Browser / Version: Waterfox 91.3.0
Operating System: Windows 10
Tested Another Browser: Yes Edge

Problem type: Site is not usable
Description: Browser unsupported
Steps to Reproduce:
Please update your browser:
It seems you are using an old or unsupported browser. To continue enjoying Canva, please update to a recent version of one of the following browsers:
Chrome, Firefox, Safari, Edge.

Opened originally on https://github.com/webcompat/web-bugs/issues/91276

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment] 2022-04-04 13:50
Duplicate of #2634

**Closed as completed by adamp01** 2022-04-04 13:50 UTC
Labels: bug
