### ISSUE TITLE
Automatic update from Current 2020-10 to G3 breaks browser & causes data loss

### ISSUE THREAD

**Issue by joberreiter** [MrAlex94/Waterfox#1837] opened 2020-11-23 18:28 UTC
**Describe the bug**
Automatic update from Current 2020-10 to G3 breaks browser completely:
- Bookmark bar gone,
- previous existent bookmarks do not exist anymore,
- rendering errors an waterfox "What is new" homepage site,
- addons silently disappeared,
- ...

But it becomes worse than that: Download of "Current 2020-10" version not possible anymore on the normal download page (only possible when navigating to  [cdn.waterfox.net](https://cdn.waterfox.net/releases/win64/installer/)).
Ans it's not even possible to reinstall 2020-10 without automatically re-updating to G3 on the next run, if the automatic updates have been turned on (which is the default preference)!

**To Reproduce**
Unfortunately no steps were taken by the user, upgrade from 2020-10 to G3 was done without user intervention.

**Expected behavior**
Ask the user if he wants to upgrade to G3 (aka distinguish between "Automatically Update" and "Automatically Upgrade").  
At _least_, backup data before automatic upgrading.

**My configuration**
 - Device: PC
 - OS: Windows 7 SP1 64bit
 - Version: Current 2020-10

**Comment by mwip** [comment] 2020-11-24 08:56
I can confirm that for the linux install as well.

```
XPCOMGlueLoad error for file /home/user/.local/bin/.waterfox/libmozsqlite3.so:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/user/.local/bin/.waterfox/libmozsqlite3.so)
Couldn't load XPCOM.
```

redownloading the .tar.bz2 resulted in the same issue

**Comment by hawkeye116477** [comment] 2020-11-24 10:29
@mwip There is a way to solve that. Just download one of the unofficial packages from https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-g3-kpe or AppImage => https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/waterfox-g3-latest-x86_64.AppImage.mirrorlist.

**Comment by praecipitator** [comment] 2020-11-24 18:26
It seems G3 forcefully creates a new empty profile and sets it as default. Running it with -P and selecting my proper default profile fixed this.

No idea who thought doing this would be a good idea, but please, never do this again.

Edit: turns out, that even if you do this, it will still insist on using it's new profile next time it starts. Found no way to make the setting stick. Attempted to downgrade, suddenly it refused to load the old profile at all.

I am sorry, but I just went back to Firefox. This just got too risky/unreliable for me.

**Comment by MrAlex94** [comment] 2020-11-25 12:35
> No idea who thought doing this would be a good idea, but please, never do this again.

Clearly this isn't meant to happen - but a lot of people have oddly named profiles and I'm not sure how. By any chance was the profile you tried to use `{RandomString}.default`?

> Edit: turns out, that even if you do this, it will still insist on using it's new profile next time it starts. Found no way to make the setting stick. Attempted to downgrade, suddenly it refused to load the old profile at all.

Use `--allow-downgrade`.

> I am sorry, but I just went back to Firefox. This just got too risky/unreliable for me.

Not a problem, enjoy Firefox - it's a great browser.

**Comment by ibeladi-mrsool** [comment] 2020-11-26 11:14
@katzenpapst  @joberreiter 
I managed to recover the previous profile by going to the `/home/{USER_NAME}/.waterfox/profiles.ini` file and adding `Locked=1` to my previous profile.
I hope this might help you.

**Comment by joberreiter** [comment] 2020-11-26 16:02
@ibrahimBeladi 
Yes, thanks. I managed to go back to Current 2020-10 with the previous used profile without hassle (but I am into software development for 30+ years and I customize/switch/data exchange my firefox/waterfox/... installations regularily).
But as a regular/ordinary user, this can be a serious problem---this is why I raised the issue.

@MrAlex94 
> Clearly this isn't meant to happen.

Should I open another issue that the download of the "Current Version" is not possible via homepage anymore?

**Comment by ibeladi-mrsool** [comment] 2020-11-26 16:22
We developers tend to solve our problems ourselves, but normal people won't. And hence I opened a similar issue, #1844. 

@MrAlex94, please, just pause the automatic update until G3 stabilizes.

**Comment by MrAlex94** [comment] 2020-11-26 16:34
Appreciate the advice but I already paused automatic updates after hearing about the issues...

**Comment by MrAlex94** [comment] 2020-11-26 20:58
@joberreiter, I have a test build out if you are willing to try it (it is not signed): [Download](https://cdn.waterfox.net/releases/tests/waterfox-78.5.0.en-US.win64.installer.exe).

If you override the install at `C:/Program Files/Waterfox Current` you should be able to access your old profile in `about:profiles`.

**Comment by joberreiter** [comment] 2020-11-27 21:04
I can confirm, this works better than G3.0.0. Old profiles are correctly loaded, bookmarks and apps are ok as far I can test.

**Comment by Peacock365** [comment] 2020-11-28 19:52
@hawkeye116477

May also want to check out these bugs: https://github.com/MrAlex94/Waterfox/pull/1820

**Comment by MrAlex94** [comment] 2020-11-30 15:07
These issues should be resolved in G3.0.1

**Closed as completed by MrAlex94** 2020-11-30 15:07 UTC
Labels: bug
