### ISSUE TITLE
Waterfox returns "This address is restricted" when accessing Plex Server stopping access

### ISSUE THREAD

**Issue by warpfactor999** [MrAlex94/Waterfox#2066] opened 2021-04-25 18:21 UTC
Can no longer access Plex on my laptop running a Plex server. This just happened with the 2021.04.1 Classic version release on a Ubuntu system. Did a refresh/reload.  Did not help. Tried overriding the blocking address using the network.security.ports.banned.override, but Waterfox pays no attention to the config setting. 
Access to Plex is ok with Firefox, Brave, and Chrome browsers, so it is unique to Waterfox. 

Also, the new website has NO reporting links or any way to report issues anymore.

**Comment by DAVe3283** [comment] 2021-04-25 21:01
I this is a duplicate of #2057

**Closed as completed** 2021-04-26 18:27 UTC
