### ISSUE TITLE
Waterfox G5.1 not rendering the corresponding emojis

### ISSUE THREAD

**Issue by gustavo-leon-lenio** [MrAlex94/Waterfox#2916] opened 2022-12-01 16:40 UTC
### What happened?

Waterfox G5.1 not rendering the corresponding emojis
<img width="230" alt="image" src="https://user-images.githubusercontent.com/99830524/205109258-d9ac5dd2-a71a-445e-b62f-3063e7e76063.png">

I have tested this on Firefox and its rendering properly
<img width="230" alt="image" src="https://user-images.githubusercontent.com/99830524/205109160-a296da2f-a406-449a-ad3d-486ce4ce9575.png">

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

### Relevant log output

```shell
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>
        <p>
            🪄 Magic Wand
        </p>
        <p>
            🇧🇷 Brazil
        </p>
        <p>
            🥑 Avocado
        </p>
    </h1>
</body>

</html>
```

**Comment by thunderstone135** [comment] 2023-01-18 03:32
**Update:**
It looks like the problem is resolved in G5.1.2.

**Comment by gustavo-leon-lenio** [comment] 2023-01-18 16:09
Yes, I confirm the issue has been fixed in G5.1.2

**Closed as completed** 2023-01-18 16:09 UTC
Labels: bug
