### ISSUE TITLE
Link to 2020.02.1-release "What's new": Not Found

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox#1452] opened 2020-02-21 19:41 UTC
https://www.waterfox.net/blog/waterfox-2020.02.1-release

from both 2020.02 Updater's notification

![Screen Shot 2020-02-21 at 20 10 19](https://user-images.githubusercontent.com/39203497/75066096-7037b180-54ea-11ea-8828-c93fc75ebd40.jpg)

and 2020.02.1 "Waterox/ About" (no need for 2nd screenshot)

Thanks Alex for the update!

**Comment by hawkeye116477** [comment] 2020-02-21 23:13
Duplicate of #1377

**Comment by LeeBinder** [comment] 2020-02-21 23:23
no, not exactly a duplicate, because https://www.waterfox.net/blog/waterfox-2020.02.1-release/ doesn't even exist, not even with a trailing slash / ;)

**Comment by grahamperrin** [comment] 2020-02-22 03:33
There's now a redirect to https://www.waterfox.net/blog/waterfox-2020.02-release/

As January's https://www.waterfox.net/blog/waterfox-2020.01-release/ was updated to include information about `2020.01.1` …

… so we can expect the February blog post to gain an update about `2020.02.1`. For this, please be patient; I imagine an update after the weekend. 

In the meantime, we have technical views of recent changes (since `2020.02`) at: 

* https://github.com/MrAlex94/Waterfox/compare/2020.02-classic...classic
* https://github.com/MrAlex94/Waterfox/compare/2020.02-current...current

----

PS for future reference, you may prefer to add web site issues (such as this) under #582

**Comment by LeeBinder** [comment] 2020-02-22 18:22
gotcha. Still, in general, whoever admins the web server needs to do some tiny bit of .htaccess magic and add a line of mod rewrite which adds a trailing slash so even URLs w/o one are being redirected properly.

Guinea pig as an example: https://www.waterfox.net/blog/waterfox-2020.02.1-release (via click onto "What's New").

I also filed this at #582

**Comment by grahamperrin** [comment] 2020-02-23 10:44
> In the meantime

Also https://old.reddit.com/comments/f749i8/-/fih77m1/?context=2

**Closed as completed** 2021-05-27 12:01 UTC
Labels: bug
