### ISSUE TITLE
Request for G4 Waterfox to at least have an option to use it without SSE 4.2 instructions.

### ISSUE THREAD

**Issue by InvisibleManX** [MrAlex94/Waterfox#2332] opened 2021-10-20 12:03 UTC
The problem is that I saw indications that G4 Waterfox won't run on CPUs without SSE 4.2 

It won't even cover Intel Core 2 Duo processors (which support SSE 4.1 )

**The reasoning for this feature request:** 

The Main competition, **Firefox** and **Chrome**. 
Their recent versions support even **SSE 2**

Also, they all work on Windows 7 SP1 (I did hear rumors that Win 7 support will be dropping too, but I'm not sure).

Waterfox is a niche browser with a lot smaller userbase, and it surivived at offering advantages over its competitors. 
But such extreme limitations make no sense.

Though, if you make it an option to disable the need for SSE 4.2 (SSE 3 would be a good target, if it's impossible to go bac kto SSE 2), it would prevent losing some of the userbase to Waterfox's competitors. They could choose to run the browser less optimized but still run it, just like Firefox or Chrome can run!

Or even simpler: it can detect if CPU supports SSE 4.2 or not, and enable/disable the speed optimization without any user even knowing it's doing so.

As an example: I"ve seen major companies in recent years, including 2021 limiting their new software to SSE 3, which is reasonable. 4.2 is just way too extreme to do it, especially when there are other alternatives around that still support SSE 2

Some very modern games sometimes have the same limiations, but it makes sense for games, because modern games will normally run well only on very modern computers which would support all that anyways.

I really think this should be seriously considered, before it's too late.

**Comment by MrAlex94** [comment] 2021-10-20 13:11
Duplicate of #2327 - no need for another issue.

**Closed as completed by MrAlex94** 2021-10-20 13:11 UTC
Labels: enhancement
