### ISSUE TITLE
Port Blocking Issue

### ISSUE THREAD

**Issue by B-IT** [MrAlex94/Waterfox#2061] opened 2021-04-23 18:46 UTC
WTF !!!  
Shitty Port blocking !!!
Back to old Version !!

Please Remove the Port Blocking from Version 2021.04.1  !!

**Comment by wkuzma** [comment] 2021-04-23 19:52
How to ublock port 3000

**Comment by wkuzma** [comment] 2021-04-23 19:54
I tried to add network.security.ports.banned.override as a string with port 3000  but it does not work.

**Comment by Peke** [comment] 2021-04-23 20:16
Reverted back to 2021.03 and blocked updates till this is fixed. using network.security.ports.banned.override ; 1-65535 did not work.

**Comment by Peke** [comment] 2021-04-23 20:19
Duplicate of #2057

**Comment by wkuzma** [comment] 2021-04-23 23:40
where can I get a copy of  2021.03 to revert back to?

**Comment by Owdjim** [comment] 2021-04-23 23:49
Yep - completely blocked the world-wide network of KiwiSDR ham radios which use port 8073. network.security.ports.banned.override appears to be ignored. Also blocked from managing any device on my own LAN for heavens sake!

**Comment by wkuzma** [comment] 2021-04-24 00:00
I found and reverted to Waterfox 2021.02 Release no my necessary port 3000 is no longer blocked for myself 
of Course I have no idea if others are blocked from my web site at port 3000 once they do the update

**Comment by goofyas007** [comment] 2021-04-24 07:29
Second that, override is ignored.
Please fix ASAP, like mentioned above, local LAN services are not accessible.

**Comment by justsonic** [comment] 2021-04-24 09:29
I had the same problem - the port 83 is restricted:

> This address is restricted
> This address uses a network port which is normally used for purposes other than Web browsing. Waterfox has canceled the request for your protection.

Adding ports to network.security.ports.banned.override parameter does not help.
I install the old version of Waterfox Classic and disable updates, but it still updating and stops working.

HELP!!!!

**Comment by W-Geronius** [comment] 2021-04-24 16:50
same problem on port 8080 within my local network (!), which definitely is a standard HTTP port that must not be blocked.
Waterfox classic 2021.04.1 (64-Bit) - found no solution other than installing 2021.03
Please fix !

**Comment by Killogy** [comment] 2021-04-24 21:29
I don´t know if related to this port problem but I can´t play Acestream stream on ArenaVision https://arenavision.site . Reinstalling Waterfox 2021.03 fixed the problem. 

Stream load from http://127.0.0.1:6878

**Comment by waltrothfuss** [comment] 2021-04-25 14:24
I use the Linux version of Syncovery for daily backups of our data drives to a Linux network server.  Syncovery uses the browser, just like webmin does; int his case it uses localhost:8999..  Syncovery no longer works with this latest update blocking all ports.  PLEASE PUT IT BACK THE WAY IT WAS.  I reverted back to the 2020.08 version to get my system working again, as this is the one I still had in a Downloads folder, and blocked updates.

**Comment by hawkeye116477** [comment] 2021-04-26 13:36
Fixed version (with patch from #2062) for Linux is available as AppImage now => https://appimage.github.io/Waterfox_Classic/. For some distros it's also on my repos => https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-classic-kpe.

**Comment by waltrothfuss** [comment] 2021-04-26 19:33
I just downloaded it, changed permissions to make it executable on my LinuxMint Mate ThinLinc terminal server, and it does now load my Syncovery web application at localhost:8999.

Thank you.

Walt

________________________________

**Closed as completed** 2021-04-28 15:11 UTC
