### ISSUE TITLE
Autocomplete window doesn't open when clicking on address bar in latest release

### ISSUE THREAD

**Issue by LegeApp** [MrAlex94/Waterfox#3128] opened 2023-08-24 08:56 UTC
### What happened?

Like title says, before the latest release, which I updated today, August 24 2023, I could click the address bar and see the autocomplete/suggestions list and click another address easily to change websites. After this release, I can't, and I don't see the option in about:config to change it. But either way, it is annoying that the default option changed. I want it back the way it was so I dont have to start typing to see the autocomplete/suggestions window in the address bar.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by ghost** [comment] 2023-08-26 17:16
Also affects G6.0.0 Beta 3.  Rolling back to Beta 2 is the only workaround I can find.

**Comment by ghost** [comment] 2023-09-07 02:46
> Also affects G6.0.0 Beta 3. Rolling back to Beta 2 is the only workaround I can find.

Bug still exists in G6.0.0 Beta 4.

**Comment by ghost** [comment] 2023-09-19 05:02
> > Also affects G6.0.0 Beta 3. Rolling back to Beta 2 is the only workaround I can find.
> 
> Bug still exists in G6.0.0 Beta 4.

And still present in G6.0.0 Beta 5.

**Comment by MrAlex94** [comment] 2023-09-26 10:02
I changed some of the preferences for G6.0, which closer aligns to how it was in G5. Is that any better? I'm not sure _exactly_ what you were having issues with, so if you have screenshots that would be helpful.

**Comment by ghost** [comment] 2023-09-26 14:56
> I changed some of the preferences for G6.0, which closer aligns to how it was in G5. Is that any better? I'm not sure _exactly_ what you were having issues with, so if you have screenshots that would be helpful.

Hard to screenshot this, as it's a change in the "on click" mouse event behavior of the urlbar.  In 6.0b2 and earlier, clicking into the urlbar causes it to act like a drop-down widget where it expands to show the top eight sites that you most frequently visit.

Starting with 6.0b3 through 6.0 final, this behavior no longer works.  Clicking into the urlbar just gives it the keyboard input focus, but doesn't drop down the list of most-visited sites anymore.  For that, you now have to take an extra action and press the down arrow key to activate the drop-down functionality.

I don't think this change was specifically intended, hence I think it's a minor regression between 6.0b2 and 6.0b3.  If this change was intentional and will remain going forward, then can you detail out the exact `about:config` defaults you updated so I (and others) can try to get back to the older behavior?  I took a quick look at the available `browser.urlbar.*` tunables in `about:config`, but nothing really stood out to me as specifically affecting the urlbar's drop-down behavior.

Hopefully that better clarifies the issue.  It's really been the only show-stopper for me in the Waterfox 6.0-series, and I am still running 6.0b2 for now until a resolution is found or I can find the right `about:config` tweaks to adjust in the 6.0 final build.  Thanks!

**Comment by MrAlex94** [comment] 2023-09-26 16:37
Ahh! I've got it now. You can change that by setting `browser.urlbar.suggest.topsites` to `true`. I'll add it in the release _after_ G6.0.1 as that's about ready for release.

**Comment by MrAlex94** [comment] 2023-10-01 17:12
Will be in G6.0.3.

**Closed as completed by MrAlex94** 2023-10-01 17:12 UTC
Labels: bug
