### ISSUE TITLE
The conversation website

### ISSUE THREAD

**Issue by TonyH1234** [MrAlex94/Waterfox#2565] opened 2022-02-07 09:20 UTC
### What happened?

Images are not displaying at theconversation.com
Firefox and Chrome don't have this problem.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by ksy36** [comment] 2022-02-08 01:53
This is a duplicate of https://github.com/WaterfoxCo/Waterfox/issues/2529

**Closed as completed** 2022-02-21 14:24 UTC
Labels: bug
