### ISSUE TITLE
Waterfox Current GLIBC_2.27 not found 

### ISSUE THREAD

**Issue by galstudio** [MrAlex94/Waterfox#1222] opened 2019-10-24 12:28 UTC
Ubuntu 16.04 at startup appears:

/opt/waterfox/waterfox
XPCOMGlueLoad error for file /opt/waterfox/liblgpllibs.so:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /opt/waterfox/liblgpllibs.so)
Couldn't load XPCOM.

installed in the system GLIBC_2.23 latest version

what to do?

**Comment by hawkeye116477** [comment] 2019-10-24 12:50
That's duplicate of #1128. Also copying it to root-owned directory isn't good, cuz updates from UI won't work.
Just install it from my apt repository following with instructions on https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-beta, but currently version is little outdated, so you will need to wait for new version, which should be maybe today or tomorrow  (I'll push it today for building, but currently OBS scheduler doesn't want to publish packages, so I guess that's will be rather tomorrow. Sometimes it makes me that joke, so I will need to wait few hours or one day.).

**Comment by galstudio** [comment] 2019-10-27 05:43
thank :)

**Comment by hawkeye116477** [comment] 2019-10-28 18:30
@galstudio https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-current-kpe

**Comment by galstudio** [comment] 2019-10-29 16:48
thank!!!!!

**Comment by galstudio** [comment] 2019-10-29 16:49
how to set the language?

**Comment by hawkeye116477** [comment] 2019-10-29 16:55
@galstudio Just install `waterfox-current-i18n-yourlangcode` package and language should be detected and set automatically.

**Comment by galstudio** [comment] 2019-10-29 18:06
thanks, set

**Closed as completed** 2021-05-27 11:56 UTC
