### ISSUE TITLE
The MEGA site can't be fully loaded but to pop an error box

### ISSUE THREAD

**Issue by nomosaic** [MrAlex94/Waterfox#2058] opened 2021-04-23 11:32 UTC
Win7 SP1  Waterfox Classic x64 2021.4.1
To visit any mega.nz or mega.co.nz site, they show me this
![mega error waterfox](https://user-images.githubusercontent.com/14254798/115864917-29d14000-a46a-11eb-8d2f-64e0d9785186.jpg)

**Comment by code-issues-pull** [comment] 2021-04-23 12:46
mega.co.nz loads fine for me. Similar setup just Win10.

Tried a clean profile?

**Comment by Squall-Leonhart** [comment] 2021-04-23 18:10
> mega.co.nz loads fine for me. Similar setup just Win10.

It's a fault caused by the bundling of ucrtbase.dll 10.17134.12
On windows 10 the system version of this dll is always used so you won't experience the issue, the problem was resolved in 17134.191.

> Improves the ability of the Universal CRT Ctype family of functions to handle EOF as valid input. KB4340917

@nomosaic replace the copy of this dll in the waterfox install folder with that attached
[ucrtbase.zip](https://github.com/MrAlex94/Waterfox/files/6367293/ucrtbase.zip)

I've tried a number of times to get Alex's attention to this problem and either use a newer/older MSVC toolset, to no avail.

**Comment by Killogy** [comment] 2021-04-23 19:36
I´m running Win7 SP1 Waterfox Classic x64 2021.4.1 and Mega is loading without errors.

**Comment by MrAlex94** [comment] 2021-05-27 15:49
@Squall-Leonhart, just FYI Classic does use the latest Windows 10 SDK - please test next release and check.

**Closed as completed by MrAlex94** 2021-05-27 15:49 UTC
