### ISSUE TITLE
wiki pics are dead 

### ISSUE THREAD

**Issue by viogq** [MrAlex94/Waterfox#1187] opened 2019-10-06 08:18 UTC
renew pics or allow other people to do it  at https://github.com/MrAlex94/Waterfox/wiki

use https://put.re/  for pics rather than bancrupted  **tinyPIC**

https://camo.githubusercontent.com/3099dcebb0aef5869888a3e3bc62733826615571/687474703a2f2f6936362e74696e797069632e636f6d2f7435323661392e706e67

**Comment by grahamperrin** [comment] 2019-10-06 10:19
Thanks, duplicate of https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-535328391

(Alex preferred to have a single issue for all such things.)

**Comment by grahamperrin** [comment] 2019-10-27 07:07
@viogq https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-535328391 is resolved, you can close this issue. Thanks; and thanks to Alex.

**Closed as completed** 2021-05-27 11:56 UTC
