### ISSUE TITLE
Unsplash image loading issue.

### ISSUE THREAD

**Issue by taciturnaxolotl** [MrAlex94/Waterfox#2561] opened 2022-02-05 18:50 UTC
### What happened?

Unsplash refuses to load images. I have successfully reproduced this on Ubuntu and Pop OS. This issue doesnt happen on firefox.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by ksy36** [comment] 2022-02-08 01:53
This is a duplicate of https://github.com/WaterfoxCo/Waterfox/issues/2529

**Comment by kcoderhtml** [comment] 2022-02-08 12:47
I also have this issue on [https://Unsplash.com](https://Unsplash.com) was referred from my issue #2561.

**Closed as completed** 2022-02-21 14:25 UTC
Labels: bug
