### ISSUE TITLE
Classic 2020.07.1 (64-bit) Web pages still broken

### ISSUE THREAD

**Issue by sutex** [MrAlex94/Waterfox#1691] opened 2020-08-02 03:17 UTC
Still unable to have the page load my saved login and see the page as been logged in
in https://robertsspaceindustries.com/spectrum/community/SC

**Comment by hawkeye116477** [comment] 2020-08-02 08:49
So it's duplicate of #1656. Opening same issue over and over again rather won't help...

**Comment by Squall-Leonhart** [comment] 2020-08-02 09:45
seems to be a user profile issue, can login just fine to RSI.

**Comment by sutex** [comment] 2020-08-03 14:59
> 
> 
> seems to be a user profile issue, can login just fine to RSI.

Ok, But Ive tried with all addon disabled and still the same issue , where another browser I have no problems, so a user profile issue?

**Comment by MrAlex94** [comment] 2020-08-04 14:57
https://github.com/MrAlex94/Waterfox/issues/1656

**Closed as completed by MrAlex94** 2020-08-04 14:57 UTC
