### ISSUE TITLE
Cant see the search bar - Classic 2021-7

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2176] opened 2021-07-20 16:42 UTC
### What happened?

I cant see the search bar below the "ROMs / Search for a specific ROM:" in the site https://edgeemu.net/ - this worked in the previous version and it works on firefox 90.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Killogy** [comment] 2021-07-20 16:56
It works for me. https://imgur.com/0EYe1Ei

**Comment by Killogy** [comment] 2021-07-20 17:00
its there if you click on it, simply search box border is missing or is transparent, when you click then search border appear.

**Comment by Felipefpl** [comment] 2021-07-20 17:04
I know but still a bug. ;)

**Comment by hawkeye116477** [comment] 2021-07-20 17:04
It's duplicate of #2168.

**Closed as completed** 2021-07-21 08:31 UTC
Labels: bug
