### ISSUE TITLE
Waterfox classic crashes on https://ec.cando-web.co.jp/

### ISSUE THREAD

**Issue by alice0775** [MrAlex94/Waterfox#2128] opened 2021-06-10 22:44 UTC
```

### Describe the bug
Waterfox classic crashes on https://ec.cando-web.co.jp/ .
Browser also crash with New profile, Safe-mode as well as  Disabling HWA.
in case of e10s is enabled: tab crashes immediately.
in case of e10s is disabled: when mouse over <select> tag  `すべてのカテゴリ   ▼`

### To Reproduce
1. Go to https://ec.cando-web.co.jp/
2. Mouse hover over <select> tag `すべてのカテゴリ   ▼`

### Expected behavior
Nothing crash

### System (please complete the following information):
 - OS: Windows,10 Home 21H2
 - Version 2021.06
```

**Comment by Killogy** [comment] 2021-06-11 01:49
Using Ublock Origin, If you block this script https://ec.cando-web.co.jp/js/jquery.customSelect.min.js tab stopped crashing.

**Comment by alice0775** [comment] 2021-06-11 08:05
The following element has inline css. 
And it seems that combination of `-moz-appearance: menulist-button;` and `position: absolute;` causes the crash.

```
...
<select name="category-select" class="styledSelectBox hasCustomSelect" 
style="-moz-appearance: menulist-button; width: 300px; position: absolute; opacity: 0; height: 78px; font-size: 14px;">
...
```

Also, the browser has been crashing since the 2021.04 release build.

**Comment by hawkeye116477** [comment] 2021-06-12 14:42
Interesting, looks like that on Linux all is fine, but reproduced on W10.

Small update:

Looks like I tracked down the problematic part - disabling **layout.css.webkit-appearance.enabled** stops crashing.

Update no 2:

I found real fix (https://bugzilla.mozilla.org/show_bug.cgi?id=1428676), will submit PR soon.

**Comment by MrAlex94** [comment] 2021-06-21 10:36
Fixed with https://github.com/MrAlex94/Waterfox/commit/cd036268ddaaaf6530fae8346d0e75ede5256ca4, thanks to @hawkeye116477.

**Closed as completed by MrAlex94** 2021-06-21 10:36 UTC
Labels: bug
