### ISSUE TITLE
Update from 6.5.2 from 6.5.1 in Linux Mint 22 fails - libmozsqlite3.so not found

### ISSUE THREAD

**Issue by alan-wint** [MrAlex94/Waterfox#3635] opened 2024-11-26 15:51 UTC
### What happened?

After updating to 6.5.2 from 6.5.1 I got
```shell
/home/user/apps/waterfox/updater: error while loading shared libraries: libmozsqlite3.so: cannot open shared object file: No such file or directory
```

It was solved by running 
```shell
cd /home/user/apps/waterfox
LD_LIBRARY_PATH=. ./waterfox
```

Probably related to https://github.com/BrowserWorks/Waterfox/issues/3610

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
[Parent 877684, Main Thread] WARNING: g_find_program_for_path: assertion 'program != NULL' failed: 'glib warning', file /home/runner/work/Waterfox/Waterfox/toolkit/xre/nsSigHandlers.cpp:187

(waterfox:877684): GLib-CRITICAL **: 16:44:26.795: g_find_program_for_path: assertion 'program != NULL' failed
[Parent 877684, Main Thread] WARNING: g_find_program_for_path: assertion 'program != NULL' failed: 'glib warning', file /home/runner/work/Waterfox/Waterfox/toolkit/xre/nsSigHandlers.cpp:187

(waterfox:877684): GLib-CRITICAL **: 16:44:26.796: g_find_program_for_path: assertion 'program != NULL' failed
```

**Comment by ghost** [comment] 2024-11-26 17:04
If you run waterfox 6.5.1 and do the update to 6.5.2 from the menu, it uses the old updater program from 6.5.1 which doesn't have the fix.

```
richardt@Avalon:~ $ waterfox
[fluent-dom] An element named "helpus-donateLink" wasn't found in the source.
richardt@Avalon:~ $ /opt/waterfox/updater: error while loading shared libraries: libmozsqlite3.so: cannot open shared object file: No such file or directory
^C
richardt@Avalon:~ $ 
richardt@Avalon:~ $ ll /opt/waterfox/updater
-rwxr-xr-x 1 richardt richardt 75496 Nov 17 10:49 /opt/waterfox/updater

richardt@Avalon:~ $ ldd /opt/waterfox/updater
	linux-vdso.so.1 (0x00007ffc515d4000)
	libnspr4.so => /lib/x86_64-linux-gnu/libnspr4.so (0x0000777a8b5e4000)
	libplc4.so => /lib/x86_64-linux-gnu/libplc4.so (0x0000777a8b5dd000)
	libplds4.so => /lib/x86_64-linux-gnu/libplds4.so (0x0000777a8b5d8000)
	libnss3.so => /lib/x86_64-linux-gnu/libnss3.so (0x0000777a8b4a9000)
	libnssutil3.so => /lib/x86_64-linux-gnu/libnssutil3.so (0x0000777a8b477000)
	libsmime3.so => /lib/x86_64-linux-gnu/libsmime3.so (0x0000777a8b44c000)
	libmozsqlite3.so => not found
    <snip>

**Comment by ghost** [comment] 2024-11-26 22:28
+1 same issue, I can confirm  alan-wint's experience.

Same error, same fix,  with the possible differences being that my instance is on Manjaro and the browsers location is under /opt/waterfox.

**Comment by MrAlex94** [comment] 2024-11-27 08:02
Duplicate of #3610

**Closed as completed** 2024-11-27 08:02 UTC
Labels: bug

**Comment by Neurothiker** [comment] 2024-11-27 08:15
same issue , reproducible.
I can confirm alan-wint's experience as well.

**Comment by MrAlex94** [comment] 2024-11-27 14:18
Just a note that the update to 6.5.2 hasn't actually happened yet, what's happened is the 6.5.1 update binary is missing a run path, so when it tries to update, it of course fails. Set the rpath as an env var to work around the issue.

**Comment by mrmelon54** [comment] 2024-12-23 23:45
Would be nice if this is pinned temporarily for users to easily find it
