### ISSUE TITLE
Does not open the site!

### ISSUE THREAD

**Issue by roman6626** [MrAlex94/Waterfox#1218] opened 2019-10-22 06:45 UTC
Waterfox 56.2.14. Try to open the weather website: https://yandex.ru/pogoda/ The browser is hanging! This happens on other sites. Chrome browsers open such sites instantly. What is the reason? Is it possible to fix this? The same thing happens on some sites of online stores. I understand that the sites are heavy, scripted, but a modern browser should be able to open any pages in a modern web.
My laptop is not new. Core i3 CPU, 2.40 GHz, 8 Gb, Windows 7 x64. But all other browsers open all pages without problems, quickly. This only appears on legacy browsers: Basilisk, Pale Moon, Waterfox. They hang tight on this Yandex page. Why is this happening? I would like to see an explanation and correction of this fact.

**Comment by ghost** [comment] 2019-10-22 09:41
@roman6626 
It opens immediately in Waterfox 56.2.14 -Win10

**Comment by roman6626** [comment] 2019-10-22 11:09
This page does not open for me. The browser hangs tight!
Discussed this issue with Graham Perrin at Waterfox. He said this shows up on very old laptops. Why? What is missing? CPU?
Why then the chromoclones and Firefox open everything for me without problems.

**Comment by grahamperrin** [comment] 2019-10-23 06:14
> Graham Perrin … said this shows up on very old laptops. …

Some misunderstanding. 

From <https://www.waterfox.net/blog/waterfox-2019.10-release-download/#commento-comment-card-8d1cfd40eddc04bf67b7f3089ae30e9f70066bf94e74b7a948b8312971970ac6>, with added emphasis: 

>> **Not** reproducible here on a ~seven year old notebook with just 2 GB memory:
> 
> https://put.re/player/r4fJr2xE.mp4

Please watch the screen recording – the site opens, no hang, no difficulty. 

@roman6626 do you find the issue with Waterfox Classic 2019.10 (20191016181224) in **safe mode**?

- about:support

Do you find the issue with a **new profile**?

- about:profiles

**Comment by roman6626** [comment] 2019-10-23 08:55
I tried to launch a new window in private mode (on the old profile, Waterfox 56.2.14)
The page opened normally, no problem.
Checked Waterfox 56.2.14 on the new profile. The page opens.
The problem is repeated on the old profile, even if the story is completely cleared.
Probably need to look for a reason among the extensions?

**Comment by roman6626** [comment] 2019-10-23 09:00
At Waterfox Classic 2019.10, I have not watched anything yet. This version is not yet available for download.

**Comment by roman6626** [comment] 2019-10-23 09:18
Found on the net a portable version of Waterfox Current 2019.10 from Cento8. Spread out. I launched it. Everything opened without problems. It’s strange. :-)
I will wait for the version update on the official website. I want to see exactly Classic 2019.10.

**Comment by grahamperrin** [comment] 2019-10-23 12:06
> private mode (on the old profile, Waterfox 56.2.14)
> 
> The page opened normally, no problem.

Interesting. 

<strike>Is the page also OK with a private window in Waterfox Classic 2019.10 (20191016181224)? </strike> (Given the commentary under [the 2019.10 blog post](https://www.waterfox.net/blog/waterfox-2019.10-release-download/) I had assumed some use of 2019.10. Apologies if this was not the case.)

> Probably need to look for a reason among the extensions?

Try this: 

- [Extension Conflict Troubleshooter : waterfox](https://www.reddit.com/r/waterfox/comments/93x02v/extension_conflict_troubleshooter/)

**Comment by roman6626** [comment] 2019-10-23 15:17
I want to wait for the official release of Waterfox Classic 2019.10 (and Current 2019.10) And see them at work. :-)

**Comment by grahamperrin** [comment] 2019-10-23 18:30
OK, although if this issue is caused by an extension (or a preference), I should not expect the issue to be resolved by an update to Waterfox.

**Comment by roman6626** [comment] 2019-10-23 19:35
I understand. I will erase. As I find something, I’ll write. Now I can list the extensions that I have installed:
Classic Add-ons Archive
Classic Theme Restorer
Clean Uninstall
Download Status Bar
DownThemAll!
enhanced-h264ify
Extended Statusbar
Imagus
Lull The Tabs
Night Mode Pro
Pure URL
S3.Google Переводчик
Tab Mix Plus
uBlock Origin
X-notifier

**Comment by troysjanda** [comment] 2019-10-23 19:45
Seems to open quicley & cleanly Waterfox 56.2.14 classic and 2019.10 Current

**Comment by roman6626** [comment] 2019-10-25 13:14
I put the extension for convenience Simple Add-on Manager, disabled all extensions. The page is loading. So the reason is in the extensions. I will look for.

**Comment by roman6626** [comment] 2019-10-25 13:32
I found an extension that negatively impacted the opening of this page. It uBlock Jrigin 1.23.0.
I wonder why so? And how to fix it?

**Comment by Squall-Leonhart** [comment] 2019-10-25 17:00
ublock being broken is nothing new.

**Comment by roman6626** [comment] 2019-10-25 17:10
Interesting. And when was he broken? Doesn't it work at Waterfox? I have not heard anything about this. He cuts advertising.
Question: what is better to use at Waterfox instead of uBlock Origin?

**Comment by grahamperrin** [comment] 2019-10-25 20:29
### Waterfox Classic

> uBlock Origin 1.23.0.

Please: 

1. visit https://www.waterfox.net/releases/ 
2. gain a more recent build of Waterfox Classic 2019.10
3. disable automatic updates for extensions
4. install the version of uBlock Origin that was intended for browsers such as Waterfox Classic
5. refrain from updating the extension. 

See https://www.reddit.com/comments/dbry0n/-/f24hrrn/ under **Hangs and Slow**

**Comment by roman6626** [comment] 2019-10-26 14:06
This is my mistake. When updating Waterfox, for some reason, the extension uBlock Jrigin was updated.
Installed the recommended legacy-version of the extension uBlock Origin 1.16.4.11. Yandex-Weather website still does not open. Hangs tight.

**Comment by grahamperrin** [comment] 2019-10-26 16:12
OK, try uBlock Origin 1.23.0 alone in a new profile: 

- about:profiles

**Closed as completed** 2021-05-27 11:56 UTC
