### ISSUE TITLE
Waterfox not playing some Mp4/gif on pre windows 10 OSes

### ISSUE THREAD

**Issue by wtfiwinomgs** [MrAlex94/Waterfox#1608] opened 2020-06-06 20:48 UTC
**Describe the bug**
Waterfox not displaying video content or gif content on some website for pre windows 10 OS.

**To Reproduce**
1. Use any windows version other than windows 10 (Windows 7, 8, 8.1 etc)
2. Use Waterfox current 2020.06, or any previous version
3. go to this link https://cdn-assets.vulpine.owogroupllc.com/media_attachments/files/001/684/946/original/1ba4b26adcf00429.mp4
or 
4. https://vulpine.club/users/Triplefox/statuses/101492886595034350
5. video does not play.

**Expected behavior**
video should play just like in google chrome or on windows 10

**Screenshots**
https://i.imgur.com/0UgfnqI.png screenshot

**My configuration** 
 - Device: PC
 - OS: Windows 8 and 8.1
 - Version: Current 2020.06

**Additional context**

**Comment by Squall-Leonhart** [comment] 2020-06-08 00:07
duplicate of #1418

**Closed as completed** 2021-05-27 12:05 UTC
Labels: bug
