### ISSUE TITLE
 Cant Install Addons On The New Chrome Web Store On WaterFox

### ISSUE THREAD

**Issue by FIRECRAFT2534** [MrAlex94/Waterfox#3265] opened 2023-11-12 15:44 UTC
So,

Cant Install add-ons on the new web store on Water Fox .
However it Used to work earlier but with the new UI for web store  you cant download it. 

![Screenshot 2023-11-12 183610](https://github.com/WaterfoxCo/Waterfox/assets/92077217/74a3e9ef-362a-43b7-9683-f6f1a55ca4a6)

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment] 2023-11-17 17:33
Duplicate of https://github.com/WaterfoxCo/Waterfox/issues/3264

**Closed as not planned by MrAlex94** 2023-11-17 17:33 UTC
Labels: bug
