### ISSUE TITLE
Waterfox 2020.01 is still buggy.

### ISSUE THREAD

**Issue by Peacock365** [MrAlex94/Waterfox#1350] opened 2020-01-11 16:41 UTC
Using macOS 10.15.2 Catalina and Waterfox 2020.01 here.

**Comment by MrAlex94** [comment] 2020-01-11 16:42
Does this occur in Safe Mode?

**Comment by Peacock365** [comment] 2020-01-11 16:54
I have neither add-ons nor themes installed (clean install), so yes.

**Comment by hawkeye116477** [comment] 2020-01-11 17:02
Probably it's something related with `https://github.com/MrAlex94/Waterfox/commit/6c7310b20bc528c6562d4659c948d052b4fd7f38`, as I see in code some things maybe different in Mac, but I didn't have Mac, so can't test.

**Comment by MrAlex94** [comment] 2020-01-11 17:04
Hmm, currently on Catalina and can’t reproduce the issues. I’ll comb through and see if I can see what’s affecting older macOS systems.

**Comment by Peacock365** [comment] 2020-01-26 10:10
So it seems that the close / minimize / maximize button issue on macOS was fixed by: https://github.com/MrAlex94/Waterfox/commit/f7c022c92adff1cee3448068274094bf531601bd

Hopefully the status bar issue I mentioned will also get tackled before a new Waterfox version is being released.

Last but not least, it's still impossible to add extensions from AMO with a clean profile. I do not think that this issue is macOS-specific, so maybe @hawkeye116477 and @laniakea64 could also have a look at it, the efforts of @MrAlex94 notwithstanding?

**Comment by hawkeye116477** [comment] 2020-01-26 10:56
I had also problems with extensions some day, I clicked to add extension, then it showed error on AMO, but now seems all is fine. 
In case of Status Bar, currently on css it's set to not be visible in full screen mode, just like on Vivaldi.

**Comment by laniakea64** [comment] 2020-01-26 12:53
> it's still impossible to add extensions from AMO with a clean profile. I do not think that this issue is macOS-specific, so maybe @hawkeye116477 and @laniakea64 could also have a look at it, the efforts of @MrAlex94 notwithstanding?

It looks to work for me in self build from https://github.com/MrAlex94/Waterfox/commit/7ddf207b656e82702eddb3c4c5d2217a9fabaf22 .  What specific extension(s) were you trying to add and what happened instead of them being added?

**Comment by Peacock365** [comment] 2020-01-26 13:35
> In case of Status Bar, currently on css it's set to not be visible in full screen mode, just like on Vivaldi.

That's not a good decision IMHO. When it's enabled, it should be permanently enabled (just like Firefox until version 3.6). Could you introduce another checkbox "Enabled when in fullscreen" or something? Or change the "enabled" setting to let it be enabled in fullscreen mode as well?

> What specific extension(s) were you trying to add and what happened instead of them being added?

Nothing special, uBlock Origin in this case. When I click "Add to Firefox", nothing happens, except that the reload button shows its animation. But no download dialogue for the extension at all. Clean profile here.

**Comment by laniakea64** [comment] 2020-01-26 13:53
Do other doorhanger notifications show up for you, e.g. the notification permission request if you click "Authorize" button on https://www.bennish.net/web-notifications.html ?

If you open Browser Console (is it `Command-Shift-J` on Mac?) before clicking "Add to Firefox", do any related messages show up there when you click "Add to Firefox"?

**Comment by Peacock365** [comment] 2020-01-26 14:01
> Do other doorhanger notifications show up for you, e.g. the notification permission request if you click "Authorize" button on https://www.bennish.net/web-notifications.html ?

Yes, it showed up, using the test site you've provided. The problem is limited to adding extensions, it seems.

> If you open Browser Console (is it Command-Shift-J on Mac?) before clicking "Add to Firefox", do any related messages show up there when you click "Add to Firefox"?

_Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”)._

**Comment by hawkeye116477** [comment] 2020-01-26 14:03
`That's not a good decision IMHO. When it's enabled, it should be permanently enabled (just like Firefox until version 3.6). Could you introduce another checkbox "Enabled when in fullscreen" or something? Or change the "enabled" setting to let it be enabled in fullscreen mode as well?`

That can be done, anyway I'm not using full screen mode and I'm not sure which solution will be better. I leave this decision to @MrAlex94.

**Comment by Peacock365** [comment] 2020-01-26 14:06
> That can be done, anyway I'm not using full screen mode and I'm not sure which solution will be better. I leave this decision to @MrAlex94.

Lots of macOS use fullscreen mode, especially MacBook Air / MacBook Pro 13" users, as screen space is limited in this case. Hiding the status bar in fullscreen mode is inconsistent and makes it seem like an unintentional bug. If Vivaldi does it intentionally, then all I can say is "It sucks."...

**Comment by laniakea64** [comment] 2020-01-26 14:35
Right-click the "Add to Firefox" button, does "Save Link As..." work?

If so, can you install the downloaded xpi?
If "Save Link As" didn't work, if you "Copy Link Location" and paste it into another browser, does other browser download the xpi successfully?

**Comment by grahamperrin** [comment] 2020-01-26 14:41
> Add-ons can't be added to Waterfox Current from AMO despite being compatible with Firefox 68.x.

> impossible to add extensions from AMO with a clean profile. I do not think that this issue is macOS-specific,

No problem with a new profile with Waterfox Current 2020.01 (20200110183601) on Linux. Added Malwarebytes Browser Guard, https://addons.mozilla.org/addon/malwarebytes/

No problem with a new profile with Waterfox Current 2020.01 (20200110203003) on Windows 10. Added HTTPZ, https://addons.mozilla.org/addon/httpz/

**Comment by Peacock365** [comment] 2020-01-26 14:44
> Right-click the "Add to Firefox" button, does "Save Link As..." work?

Yes, it works. I was able to download the .xpi file this way.

> If so, can you install the downloaded xpi?

Yes, it works. Just installed uBlock origin using the downloaded file.

Everything seems to work except adding the add-on directly via the "Add to Firefox" button on AMO.

**Comment by laniakea64** [comment] 2020-01-26 15:43
Does it make any difference if you set `about:config` > `privacy.resistFingerprinting.block_mozAddonManager` to `false`?

**Comment by Peacock365** [comment] 2020-01-26 21:08
> Does it make any difference if you set about:config > privacy.resistFingerprinting.block_mozAddonManager to false?

This makes a difference indeed. It fixes the issue, tested with several add-ons I just added to Waterfox. Thumbs up!

**Comment by Peacock365** [comment] 2020-01-26 21:14
I've created a pull request fixing the issue now.

**Comment by Peacock365** [comment] 2020-01-27 14:56
@hawkeye116477, I hope you don't take that personally, but your recent contributions seem to have affected the macOS builds of Waterfox in a very bad way. I am not holding it against you, since you can't test on macOS, but that's just the state of affairs. Other bugs I have found (no idea if macOS-specific in some cases):

- When tab positions "Top under address bar" or "Bottom" are selected, there is a weird bar on top of the address bar with no content, which wastes precious screen space (could be macOS-specific).
- When the bookmarks bar and the tabs are both on bottom, the tabs are under the bookmarks bar. Not sure if this is intended.

**Comment by hawkeye116477** [comment] 2020-01-27 15:43
@Peacock365 In case of `Window Controls position` I changed it recently to be only for Linux for now.
I added some additional improvements few days ago (made it more faithful to original), just try compiling with latest commit.


`When the bookmarks bar and the tabs are both on bottom, the tabs are under the bookmarks bar. Not sure if this is intended.`
Yes, this is intended.

![Screenshot_20200127_172740](https://user-images.githubusercontent.com/19818572/73193099-5644c200-412a-11ea-8a41-7b9a424badd3.png)

**Comment by Peacock365** [comment] 2020-02-29 09:52
@hawkeye116477 

New graphical issue:

- When bookmarks bar is set to be on bottom, it doesn't disappear when YouTube videos go to fullscreen.
- When the status bar is activated, it doesn't disappear when YouTube videos go to fullscreen.

Not a graphical issue, but a fix for a stupid design decision on Mozilla's part:

- When the browser is in fullscreen mode (with title bar disabled, that's important!), there is a weird square (unused space) left of the first tab. This is intended by Mozilla, but it's stupid. This can be fixed by the following CSS:

https://www.reddit.com/r/FirefoxCSS/comments/ao3p5k/ff_65_remove_space_from_top_left_corner/

Please @hawkeye116477, consider implementing this.

**Comment by hawkeye116477** [comment] 2020-02-29 10:16
> 
>     When bookmarks bar is set to be on bottom, it doesn't disappear when YouTube videos go to fullscreen.
>     When the status bar is activated, it doesn't disappear when YouTube videos go to fullscreen.
> 

In case of this, I have no idea how to resolve that without hiding that for full screen mode. Tried `visibility: collapse`, but seems that's not working.

**Comment by Peacock365** [comment] 2020-02-29 10:28
@hawkeye116477 

What about the second issue:

- When the browser is in fullscreen mode (with title bar disabled, that's important!), there is a weird square (unused space) left of the first tab. This is intended by Mozilla, but it's stupid. This can be fixed by the following CSS:

As for the problem you have encountered, maybe we could ask @Aris-t2, he is quite an expert for all issues related to UI?

**Comment by hawkeye116477** [comment] 2020-02-29 20:27
`When the browser is in fullscreen mode (with title bar disabled, that's important!), there is a weird square (unused space) left of the first tab. This is intended by Mozilla, but it's stupid. This can be fixed by the following CSS:`

Are you sure that's in full screen mode? I see that problem only when it's not maximized and same is on screenshot on reddit.

**Comment by Peacock365** [comment] 2020-02-29 20:43
Fullscreen mode = Maximize, on macOS. When you hit the green button on macOS, the window maximizes, it covers the entire screen. It still displays the application's UI, so it is not a "fullscreen mode" like on other OSes, where the UI is entirely hidden.

This should fix the design flaw on all OSes:

https://old.reddit.com/r/FirefoxCSS/comments/ao3p5k/ff_65_remove_space_from_top_left_corner/efxzkwt/

**Comment by Peacock365** [comment] 2020-02-29 20:49
Or this, might be even better:

https://old.reddit.com/r/FirefoxCSS/comments/em563z/how_can_i_remove_this_space_from_my_tab_bar_thanks/fdmmvb2/

**Comment by hawkeye116477** [comment] 2020-02-29 20:50
https://github.com/MrAlex94/Waterfox/pull/1466/commits/8a49730d9455d0dfae1e1e801b16288a1ebe16a0

**Comment by Peacock365** [comment] 2020-02-29 20:57
@hawkeye116477, you are unironically my hero.

**Comment by Peacock365** [comment] 2020-02-29 21:00
The last thing I have noticed:

- When any of the themes with rounded tabs are used (no matter whether Australis Light or Australis Dark), the new tab button is still pretty edgy. It used to be rounded up to and including Waterfox 68.0b1, but after that @MrAlex94 seemed to have introduced a change that reverted the new tab button back to its old, non-australized form. 

Any thoughts?

**Comment by Peacock365** [comment] 2020-03-04 09:03
@MrAlex94 @hawkeye116477 

Would it be possible to make the status bar customizable? I totally would like to drag icons to the status bar, but it seems to be static, which is most unfortunate. If it can't be made customizable, how did @hawkeye116477 manage to set the sidebar and zoom icons there?

And a kind reminder of course:

- When any of the themes with rounded tabs are used (no matter whether Australis Light or Australis Dark), the new tab button is still pretty edgy. It used to be rounded up to and including Waterfox 68.0b1, but after that @MrAlex94 seemed to have introduced a change that reverted the new tab button back to its old, non-australized form.

**Closed as completed** 2021-05-27 11:59 UTC
Labels: bug
