### ISSUE TITLE
Tab interaction area doesn't go to top of window

### ISSUE THREAD

**Issue by ThirteenSpades** [MrAlex94/Waterfox#2865] opened 2022-10-17 04:26 UTC
On the old Waterfox theme, and pretty much every other browser, I can throw my mouse to the top of the tab and click and it will register it and go to that tab, but with the new Waterfox theme (which I adore) the small area above every tab doesn't register clicks.  I'd like it to register clicks up to the window border so I can throw my mouse to the top of my screen and click a tab without having to bring it down a small bit every time to click the tab I want.

**Comment by adamp01** [comment] 2022-10-17 10:37
Hi,

We had another report of this and I did try to replicate on Windows 10 and Mac but failed to.

Which operating system are you on? And in `about:config` the preference `userChrome.padding.drag_space` should either not exist or be set to false.

**Comment by adamp01** [comment] 2022-10-17 10:42
And is `userChrome.theme.enable` true or false?

**Comment by PrussianJaeger** [comment] 2022-10-18 23:07
Hey, I'm ThirteenSpades, this is my current account, I forgot I was logged into that old one.

I'm on Windows 10.  userChrome.theme.enable is true, as for userChrome.padding.drag_space check the attachments.
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/99280992/196561545-dd1d749f-7553-4512-916e-6141ca699f33.PNG">
<img width="960" alt="Capture2" src="https://user-images.githubusercontent.com/99280992/196561547-fb85970e-c4c9-48c3-ad32-4f56c644678f.PNG">

**Comment by adamp01** [comment] 2022-10-20 09:51
Could you try flipping this pref to `true` please: `userChrome.compatibility.os.windows_maximized`

**Comment by ThirteenSpades** [comment] 2022-10-21 01:25
Didn't fix it

**Comment by adamp01** [comment] 2022-10-21 08:39
I believe you would have to restart the browser as well, should have mentioned that before

**Comment by PrussianJaeger** [comment] 2022-10-23 04:07
I did, it didn't change the issue

**Comment by adamp01** [comment] 2022-10-25 09:15
I will need your help testing some things to try and resolve this one. Here is a related issue for the theme: https://github.com/black7375/Firefox-UI-Fix/issues/384

Would you be able to open the browser toolbox (Tools -> Browser Tools -> Browser Toolbox) and accept any prompt that appears. This will then let you modify browser window CSS directly. 
If you search for `titlebar` in the Inspector tab you should find the correct element to play with. The layout tab on the right hand side might give some indications as to what is causing the additional pixels at the top, either margin or padding.
Otherwise test out some options for reducing `margin-top` or `padding-top` and please let me know if anything there resolves this so I can adjust.
<img width="910" alt="image" src="https://user-images.githubusercontent.com/47503375/197734231-7808efc2-6903-4595-aa81-c1d897755d5d.png">

**Comment by PrussianJaeger** [comment] 2022-10-27 22:24
Since the new update, it has been fixed on my laptop; I didn't implement any of the changes you requested.

Before the update, I also noticed on my desktop (1440p screen at 125% scaling) that the minimize, maximize, and close buttons also did not go the top; I have not yet checked if the new update fixed it on my desktop.

Attached is a screenshot of what the browser CSS is currently on the newest update on my laptop; I will let you know if my desktop is fixed once I use it.
<img width="960" alt="Capture3" src="https://user-images.githubusercontent.com/99280992/198409281-6cb4e320-8a70-4b45-a768-ea1cec79ba03.PNG">

**Comment by PrussianJaeger** [comment] 2022-11-03 02:57
The issue persists on my desktop with the same issue of the buttons not going to the top either; I'm not proficient at all in the CSS stuff, is there anything I can do?

**Comment by adamp01** [comment] 2022-11-03 13:53
As it seems to be all good on the laptop, but not the desktop, would you be able to share the preference names/values from `about:config` when you search for `userChrome.` on each machine please? This will allow me to identify if there is a disparity between the two that might be impacting this.

**Comment by PrussianJaeger** [comment] 2022-11-03 23:40
Here it is from my laptop, I will post my desktop once I'm on it later tonight.

<img width="960" alt="Capture4" src="https://user-images.githubusercontent.com/99280992/199855257-1c0f81bd-9c04-43cc-90bb-4a5f3b1111f9.PNG">
<img width="960" alt="Capture5" src="https://user-images.githubusercontent.com/99280992/199855266-0947f765-e2c6-425b-b6ab-d0d6fa74fb71.PNG">
<img width="960" alt="Capture6" src="https://user-images.githubusercontent.com/99280992/199855272-73d94747-c06d-4ef9-b552-2f5881f0951e.PNG">
<img width="958" alt="Capture7" src="https://user-images.githubusercontent.com/99280992/199855283-3acf20ba-88e3-4a4f-82e8-2f7f329e812d.PNG">
<img width="960" alt="Capture8" src="https://user-images.githubusercontent.com/99280992/199855288-c1b5cc79-8213-4c27-ba53-c810252b451d.PNG">

**Comment by PrussianJaeger** [comment] 2022-11-05 00:24
Here's my desktop.

![Capture3](https://user-images.githubusercontent.com/99280992/200092331-5ba0f71f-ec64-459c-adf7-d3d9ad2fefcc.PNG)
![Capture4](https://user-images.githubusercontent.com/99280992/200092334-9c886cfe-8077-40e5-a999-91ac3b07e97e.PNG)
![Capture5](https://user-images.githubusercontent.com/99280992/200092417-3975167b-6024-4f8b-bce9-11cb3a797926.PNG)

**Comment by PrussianJaeger** [comment] 2022-11-07 21:35
On my work computer, which is 1080p, the issue is also absent.

**Comment by PrussianJaeger** [comment] 2022-11-16 20:18
Since G5.1, the issue appeared on my work machine after I re-enabled the Waterfox customizations for every theme.

**Comment by JoshDavis97** [comment] 2022-11-17 00:08
This is impacting me too, since upgrading to G5.1 earlier today. 1080p resolution, window maximized, Win10 Home build 19043.2251. I had no such issues before updating today.

**Comment by repingl** [comment] 2022-11-17 07:47
Update to G5.1 today introduced this issue for me as well. 

**Fullscreened:**
![image](https://user-images.githubusercontent.com/6507668/202386642-63841148-a4da-4efe-a30c-713cbff3a424.png)

**Not fullscreened (blue is windows background):**
![image](https://user-images.githubusercontent.com/6507668/202386481-ab5cb753-7105-4c0f-987a-e609dd5ff331.png)

Windows 10 Pro N, build 19045.2251

EDIT: tested suggested solutions:
- userChrome.padding.drag_space was already false
- userChrome.theme.enable was already true
- userChrome.compatibility.os.windows_maximized was already true
- browser CSS via Browser Toolbox shows the culprit:
![Untitled1](https://user-images.githubusercontent.com/6507668/202389340-c2cb9bea-777a-4bd6-aa38-a871b2b43417.png)
when the padding-top is zeroed out, it fixes this, but I don't know how to keep this change (reverts after restart)

EDIT2:
flipping **userChrome.compatibility.os.windows_maximized** to **false** fixed it for me

**Comment by MrAlex94** [comment] 2022-11-17 09:36
Glad you've found a fix for this. For what it's worth, if you are all still having issues with this, please submit to the theme repository: https://github.com/black7375/Firefox-UI-Fix

**Closed as completed by MrAlex94** 2022-11-17 09:36 UTC
Labels: enhancement
