### ISSUE TITLE
Waterfox 2020.1 classic doesn't work in Ubuntu 16.04

### ISSUE THREAD

**Issue by jcea** [MrAlex94/Waterfox#1356] opened 2020-01-12 18:20 UTC
Waterfox classic 2019.12 worked fine.

Ubuntu 16.04 is supported until 2021/04. More than a year to go.

Trying to launch just released Waterfox classic 2020.1 I get this error:

```
jcea@jcea:~$ waterfox/waterfox
XPCOMGlueLoad error for file /home/jcea/waterfox/libnspr4.so:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /home/jcea/waterfox/libnspr4.so)
Couldn't load XPCOM.
```

Since this is a security release, I think solving this should be a priority.

Thanks a lot for your time and effort.

**Comment by hawkeye116477** [comment] 2020-01-12 18:31
You can also install it from unofficial apt repository => https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-classic-kpe
or as AppImage => https://appimage.github.io/Waterfox_Classic/.

**Comment by laniakea64** [comment] 2020-01-12 18:42
Duplicate of https://github.com/MrAlex94/Waterfox/issues/1128

**Comment by jcea** [comment] 2020-01-12 18:44
Sorry, @hawkeye116477, but I don't know who are you and I rather prefer not to use random stuff downloaded from unknow places :-) Please, do not consider this an insult, only a "caveat emptor". Do you mind to share your credentials?

**Comment by jcea** [comment] 2020-01-12 18:48
> Duplicate of #1128

That issue refers to current. This is about classic :-).

**Comment by hawkeye116477** [comment] 2020-01-12 18:55
Credentials? I think that source files which I used to make packages should clarify the matter a bit:
```
https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage
https://build.opensuse.org/package/show/home:hawkeye116477:waterfox/waterfox-classic-kpe
https://build.opensuse.org/package/show/home:hawkeye116477:waterfox/waterfox-classic-appimage
```
Anyway I also made few commits to Waterfox's repo.

**Comment by MrAlex94** [comment] 2020-01-12 19:12
I can vouch for @hawkeye116477. Of course no guarantees as I am not omniscient, but they have been contributing and helping Waterfox for a while :-)

**Comment by lproven** [comment] 2020-01-13 14:21
Same issue on openSUSE Leap 15.1, fully updated -- W'fox 2020.01 does not run with the same

> Couldn't load XPCOM.

... error as in the root post (with slightly different paths because of a different distro).

**Comment by lproven** [comment] 2020-01-13 18:02
(AppImage works fine so have temporarily switched to that, but it breaks system integration, e.g. pinning the app to the taskbar.)

**Comment by hawkeye116477** [comment] 2020-01-13 19:00
@lproven You can also extract AppImage (https://docs.appimage.org/user-guide/run-appimages.html?highlight=extract#extract-the-contents-of-an-appimage) or try rpm package from repository or use appimaged or AppImage Launcher to have system integration.

**Comment by morninglite** [comment] 2020-01-13 20:22
It's not only Ubuntu 16.04, it's also Ubuntu 18.04 (the latest LTS release), and all versions of Debian, Linux Mint, openSUSE and others.

Basically only bleeding edge distros like Arch, Fedora and non-LTS Ubuntu releases can use this Waterfox build. As far as I know, the vast majority of Linux desktops cannot use it.

**Comment by jcea** [comment] 2020-01-14 17:18
> I can vouch for @hawkeye116477. Of course no guarantees as I am not omniscient, but they have been contributing and helping Waterfox for a while :-)

What I don't understand is why @hawkeye116477 can provide a compatible release just compiling and @MrAlex94 has not done the same to release an official 2020.1 version. It is obvious that current official 2020.1 classic release is not compatible with most supported Linux distributions.

Maybe @MrAlex94 is traveling, I don't know.

**Comment by hawkeye116477** [comment] 2020-01-14 17:53
@jcea He probably used some other PC with newer distro than he used for previous version. 
In case of AppImage package, it's compiled on CentOS 7 (on OBS VM), so it's even more compatible than official Classic 2019.12.

**Comment by jcea** [comment] 2020-01-14 18:11
> @jcea He probably used some other PC with newer distro than he used for previous version.
> In case of AppImage package, it's compiled on CentOS 7 (on OBS VM), so it's even more compatible than official Classic 2019.12.

Compilation should be done in a virtual machine with the oldest supported linux distribution. My advice :-).

**Comment by ilu33** [comment] 2020-01-14 19:24
I can confirm that Waterfox classic 2020.01 does not work on debian 9 and debian 10. Waterfox classic 2019.12 worked fine.

```
/opt/waterfox-classic-test/waterfox
XPCOMGlueLoad error for file /opt/waterfox-classic-test/libnspr4.so:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /opt/waterfox-classic-test/libnspr4.so)
Couldn't load XPCOM.

ldd --version
ldd (Debian GLIBC 2.28-10) 2.28
Copyright (C) 2018 Free Software Foundation, Inc. <snip>

**Comment by zpangwin** [comment] 2020-01-18 17:26
> I can confirm that Waterfox classic 2020.01 does not work on debian 9 and debian 10. Waterfox classic 2019.12 worked fine.

Ditto for Linux Mint 19.3 (Ubuntu 18.04 based) with waterfox-classic-2020.01.en-US.linux-x86_64.tar.bz2

```
   $ /opt/waterfox-classic/waterfox
   XPCOMGlueLoad error for file /opt/waterfox-classic/libnspr4.so:
   /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /opt/waterfox-classic/libnspr4.so)
   Couldn't load XPCOM.
```

I can also confirm that the previous waterfox-classic-2019.12.en-US.linux-x86_64.tar.bz2 did not have this issue.

Can't speak for anyone else, but I am not very fond of the idea of upgrading to GLIBC_2.30 as a resolution to this issue. Primarily because (a) I am not sure what other stability issues that might introduce under 18.04/bionic base / other apps on my system, (b) while I like waterfox, the amount of effort to install updates on my system is already quite high as compared with firefox/chromium/chrome which all either appear in the central repos or have official ppa's and I don't like the idea of adding another step to the update/install process which I already am wrapping in a shell script that frequently needs updating.

**Comment by grahamperrin** [comment] 2020-01-18 18:01
https://redd.it/eogn31

**Comment by zpangwin** [comment] 2020-01-18 18:04
> https://redd.it/eogn31

awesome, thanks for sharing!

**Comment by ilu33** [comment] 2020-01-28 22:58
Build systems need to be conservative and not cutting edge - Debian oldstable (now: stretch) would be a good candidate. It's still supported with security updates but sufficiently old so that a majority of systems gets covered.
I'm not familiar with rpm based distros but an older version of CentOS might work as well. 
Just please stay away from the popular fancy stuff with their frequent updates.

**Comment by hawkeye116477** [comment] 2020-01-28 23:17
Debian 9 has glibc 2.24 and Ubuntu Xenial has 2.23, so would be a problem. Better is rather CentOS 7.
https://pkgs.org/download/glibc

**Comment by laniakea64** [comment] 2020-02-06 18:10
Official Waterfox Classic 2020.01.1 Linux build seems to run fine for me in Xubuntu 16.04, Xubuntu 18.04, and CentOS 8.  Does it work for other people?

**Comment by ilu33** [comment] 2020-02-13 15:16
No it does not work on debian10 stable (buster), although we have Glibc 2.28.
```
/opt/waterfox-classic-test/waterfox
XPCOMGlueLoad error for file /opt/waterfox-classic-test/libmozsandbox.so:
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/waterfox-classic-test/libmozsandbox.so)
Couldn't load XPCOM.

ldd --version
ldd (Debian GLIBC 2.28-10) 2.28

strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX_3.4.
<snip>
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
```
Notice the absence of 3.4.26

@MrAlex94 it would make things much easier if you decided to built waterfox in a virtual machine with a really conservative distro like debian (I'd say old-stable i.e. stretch which is LTS until 2022) or, as somebody else recommended, centos7. No Ubuntu. Please at least cover current debian stable.

**Comment by emtiu** [comment] 2020-03-13 09:42
This appear to be fixed in 2020.03

**Comment by brucerv** [comment] 2020-03-19 14:22
Still not fixed in 2020.03 for Ubuntu 16.04 LTS. 
    GLIBCXX_3.4.22 not found
Most recent version that works is waterfox-56.0.2

Is it known to work for Ubuntu 18?

**Comment by emtiu** [comment] 2020-03-19 14:41
It runs on Debian 8 (Jessie), which at first glance should be an even older base than Ubuntu 16.

**Comment by lproven** [comment] 2020-03-19 15:40
> Still not fixed in 2020.03 for Ubuntu 16.04 LTS.

There is now 2020.03.1. I suggest trying that.

WFM under openSUSE Leap 15.1, openSUSE Tumbleweed & Ubuntu 19.10.

**Comment by emtiu** [comment] 2020-04-09 14:31
.. aaaaand the problem is back with 2020.04

**Comment by dclement100** [comment] 2020-04-10 08:32
I can confirm that it doesn't work either on Debian 9 (Stretch), because of the version of GLIBC:
```
XPCOMGlueLoad error for file /opt/waterfox-classic/liblgpllibs.so:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /opt/waterfox-classic/liblgpllibs.so)
Couldn't load XPCOM.
```
Debian 9 only has 2.24 for now, so we're stuck with Waterfox-classic 2020.03.1. Hopefully Waterfox-classic, which supports old add-ons, won't let down old distros.

**Comment by mariush444** [comment] 2020-06-13 21:22
I've found solution/workaround for my Mint 18.1 (64 bit) that have Libc 2.27. Waterfox 2020.04 and above needs Libc 2.28.

I downloaded libc 2.30 from https://packages.ubuntu.com/eoan/amd64/libc6-udeb/download
then I extracted files useing command
dpkg-deb -x libc6-udeb_2.30-0ubuntu2_amd64.udeb ./tempdir

then I created folder/directory (as root) /usr/alternates/lib/x86_64-linux-gnu
put into the directory the files libm.so.6 and libm-2.30.so from tempdir/lib

then I created file ld.so.preload in /etc (as root)
the file contains only one line
/usr/alternates/lib/x86_64-linux-gnu/libm.so.6

Then waterfox 2020.06 works.
This solution should work for Ubunto and Debian. Yuo should download 32-bit libc if your system is 32-bit.

Now Waterfox uses new libc 2.30  from preloded but other programs use standard libm.so.6 (libc 2.27) from /lib/x86_64-linux-gnu/

**Comment by ilu33** [comment] 2020-07-21 15:26
Is there any official download source with old versions, especially 20.03? The website seems to only give access to the latest version. @MrAlex94 ?

**Comment by hawkeye116477** [comment] 2020-07-21 15:32
@ilu33 You can see some of links on https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads or just change version in latest URL.

**Comment by mariush444** [comment] 2020-07-22 21:26
> Is there any official download source with old versions, especially 20.03? The website seems to only give access to the latest version. @MrAlex94 ?

https://cdn.waterfox.net/releases/linux64/installer/waterfox-classic-2020.03.en-US.linux-x86_64.tar.bz2
https://cdn.waterfox.net/releases/linux64/installer/waterfox-current-2020.03.en-US.linux-x86_64.tar.bz2

**Closed as completed** 2021-05-27 11:59 UTC
