### ISSUE TITLE
Status bar NULL. It's all blank after 6.5.0 update

### ISSUE THREAD

**Issue by Mxzcabel** [MrAlex94/Waterfox#3607] opened 2024-11-08 16:36 UTC
### What happened?

After update my bottom bar displays as NULL and it ignores the theme, overriding with the white color. Switching for other themes or enabling to use system colors change nothing in the current state.

![Image](https://github.com/user-attachments/assets/d9fbfa4f-8a55-4cea-8392-37522b151783)
![Image](https://github.com/user-attachments/assets/19d04d99-e42b-4572-937c-65aa78d25403)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by Helspank** [comment] 2024-11-11 12:15
![Image](https://github.com/user-attachments/assets/b29a5518-89c7-49dd-bd1c-5a682cee1b62)

Can confirm, it happens to me as well. 
Waterfox 6.5.1 (64-bit) for Linux.

**Comment by MrAlex94** [comment] 2024-11-11 13:05
Duplicate of #3543

**Closed as completed by MrAlex94** 2024-11-11 13:05 UTC
Labels: bug
