### ISSUE TITLE
[Question]  WaterFox Current Portable?

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1270] opened 2019-11-21 16:36 UTC
Sooooo, i looked everywhere to see if there is a Portable Version of WaterFox Current available but there was none, can someone point me in the right direction?

**Comment by grahamperrin** [comment] 2019-11-21 16:47
> the right direction?

https://github.com/MrAlex94/Waterfox/issues/943#issuecomment-511145612

**Comment by TheQuickFox** [comment] 2020-04-02 22:45
Is this still on the planning?
If yes, what is the expected timeline?

**Comment by jrappen** [comment] 2020-04-09 00:03
@grahamperrin I'm not sure why you link to your posts where you link to your posts where you link to your posts where people can find an answer by somebody else. This behavior is quite exhausting. Why not link the (last) answer directly?

---

duplicate of #943

answer in the comments further down there: https://github.com/MrAlex94/Waterfox/issues/943#issuecomment-601642110

**Comment by grahamperrin** [comment] 2020-04-10 01:35
Overlooked. And/or #943 was primarily about https://portableapps.com/ and adding this second sentence has left me quite exhausted.

**Closed as completed** 2021-05-27 11:58 UTC

**Comment by timur-g** [comment] 2021-09-03 10:51
Shouldn't this stay open until it's done or declined?
There's https://github.com/portapps/waterfox-portable/releases but it doesn't update.
