### ISSUE TITLE
[Current WF] Open With by Geoff Lankow not working (Win10)

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1330] opened 2019-12-26 19:20 UTC
- I'm on Windows 10 v1809. 
- Using WF Current 2019.10. 
- Add-on works with WF Classic 2019.12. 
- Go to the add-on options page and click 'test' = fail. Obviously, it should = pass.

[https://addons.mozilla.org/en-US/firefox/addon/open-with/](url)

Edit: Also works with latest FF v.71.0
Edit: Error Message from add-on: 

- Something went wrong. There might be more information in the Browser Console.
Browser Console:

- No such native application open_with NativeMessaging.jsm:112
-   startupPromise resource://gre/modules/NativeMessaging.jsm:112

**Comment by grahamperrin** [comment] 2019-12-27 08:23
[Extension application compatibility with Waterfox Current](https://www.reddit.com/r/waterfox/comments/e76pgq/extension_application_compatibility_with_waterfox/)

**Comment by lucknaumann** [comment] 2019-12-27 18:42
Thanks for this @grahamperrin ! So, if I understand correctly, at the moment WF Current doesn't have support for external applications. Is this correct? This is a python script that installs a .bat script and two .json files. 

I also have similar extensions for other apps that use node.js. I haven't tested them yet but I'm guessing they won't work, either. I don't know what Video DownloadHelper uses but it looks like an .exe program from your screenshot. This would imply that my statement above would be correct.

**Comment by lucknaumann** [comment] 2020-02-23 23:52
BUMP. Still not working with latest release.

**Comment by grahamperrin** [comment] 2020-02-24 01:31
Link broken in the opening post ∴ for convenience, https://addons.mozilla.org/addon/open-with/

To Waterfox developers, I suggest: 

* closing this issue as a duplicate of https://github.com/darktrojan/openwith/issues/256 (I'm adding commentary there)
* collaborating on a PR in the `darktrojan` area.

**Comment by lucknaumann** [comment] 2020-02-24 02:00
To the devs - I would advise **NOT** closing this issue as I believe it is actually a Waterfox Current issue and **NOT** the add-on. Why? Because it works in _every other browser_ **including** Firefox -- _all of them_ as I have used this extension for _years_  -- and this is the **only** browser in which it **doesn't** work. And I use a lot of browsers.
Thank you.

**Comment by grahamperrin** [comment] 2020-02-24 02:02
>> I'm adding commentary 

Done; https://github.com/darktrojan/openwith/issues/250#issuecomment-590145278 includes orientation. 

> this is the **only** browser in which it doesn't work.

Not so. Please see commentary.

**Comment by grahamperrin** [comment] 2020-02-24 02:19
> essentially a clone of Firefox 

Beyond the essence, a little more detail: 

* names of binaries for Brave and for Waterfox Current differ from the name of the binary for Firefox. 

Please see for example the lines that appear in green.

**Comment by grahamperrin** [comment] 2020-03-01 19:23
Via <https://github.com/darktrojan/openwith/issues/250#issuecomment-593122337>

* (first draft) [Add support for Brave Browser and Waterfox Current by grahamperrin · Pull Request #260 · darktrojan/openwith](https://github.com/darktrojan/openwith/pull/260/)

**Closed as completed** 2020-06-08 06:38 UTC
