### ISSUE TITLE
New update broke centered tab content

### ISSUE THREAD

**Issue by HACKER097** [MrAlex94/Waterfox#3170] opened 2023-09-29 17:24 UTC
### What happened?

New update broke centered tab content

It now appears to the right.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment] 2023-10-01 17:07
Dupe of https://github.com/WaterfoxCo/Waterfox/issues/3160

**Closed as completed by MrAlex94** 2023-10-01 17:07 UTC
Labels: bug
