### ISSUE TITLE
Open All Bookmarks via Library does not function

### ISSUE THREAD

**Issue by Striker243** [MrAlex94/Waterfox#2855] opened 2022-10-11 15:57 UTC
### What happened?

Waterfox G5.0.1 (G4.1.5 & Firefox 105 work(ed) fine)

Steps to reproduce:
1. Open library and choose a folder with bookmarks inside
2. Right-click the folder and choose "Open All Bookmarks"

Expected behaviour: 
Bookmarks are getting opened as tabs.

Actual behaviour:
Nothing happens. No error message, no tabs are opening.

Workaround:
- Opening each bookmark separately via right-click and "Open in New Tab".
- Select the folder via bookmarks toolbar or via Menu Bar/ Bookmarks. Then the "Open All Bookmarks"-function is working properly.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment] 2022-10-12 15:29
Duplicate of #2827 and fixed for next release.

**Closed as completed by adamp01** 2022-10-12 15:29 UTC
Labels: bug
