### ISSUE TITLE
Please provide sha256 checksum and/or gpg signatures so that we can trust downloads

### ISSUE THREAD

**Issue by affinityv** [MrAlex94/Waterfox#1325] opened 2019-12-25 18:04 UTC
Please provide sha256 checksum and/or gpg signatures so that we can trust downloads

**Comment by AzureRaptor** [comment] 2020-03-01 08:15
I second this request.

**Comment by stanwmusic** [comment] 2020-03-25 07:32
I third this request.

**Comment by grahamperrin** [comment] 2020-03-25 19:33
Thumbs-ups alone should suffice :-) ▶ [the opening post](https://github.com/MrAlex94/Waterfox/issues/1325#issue-542372101), thanks. 

FYI, non-official (I should not ask the checksums here to be trusted): 

* https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads

Meta, tracking: #582

**Comment by affinityv** [comment] 2020-03-26 09:55
@grahamperrin thanks I've got the same sha256 for waterfox-current-2020.03.en-US.linux-x86_64.tar.bz2, how about classic though?

**Comment by affinityv** [comment] 2020-03-26 09:57
Having sha256sums are great, but signing is better.  In any case, we need both officially from the project and/or @MrAlex94 himself....

**Comment by grahamperrin** [comment] 2020-03-26 16:42
https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#2020031-classic

**Comment by affinityv** [comment] 2020-03-26 16:50
@grahamperrin thanks again, same sha256sum for waterfox-classic-2020.03.1.en-US.linux-x86_64.tar.bz2

**Comment by MrAlex94** [comment] 2021-05-27 12:00
Dupe of https://github.com/MrAlex94/Waterfox/issues/271, still planning to add.

**Closed as completed** 2021-05-27 11:59 UTC
