### ISSUE TITLE
Issue closing spree

### ISSUE THREAD

**Issue by vertigo220** [MrAlex94/Waterfox#2102] opened 2021-05-27 15:19 UTC
I just had two issue I created a while ago closed back-to-back, with no associated commits, no explanation, nothing. Taking a closer look, I see @MrAlex94 has closed a ton of issues very recently and is continuing to do so as I write this. When I first checked ~10-15 minutes ago, there were 80-something open issues, then when I came back a few minutes ago there were 74, now there are 69 and dropping. What's going on?

**Comment by Felipefpl** [comment] 2021-05-27 16:06
Either they cant be fixed now/will be fixed later, i'm favorable to it, better than let them pile up to more than 2,300 issues like on qtbittorrent. ALL devs should do a cleanup such as this one.

**Comment by MrAlex94** [comment] 2021-05-27 16:23
I set aside the day to go through issues. 
If I didn't reply:

-> Either couldn't reproduce
-> Issue is too outdated
-> Issue didn't provide enough info
-> Issue won't be fixed
-> Issue isn't even an issue report

I've replied to all I though relevant, and kept issues that can be addressed open.

**Closed as completed by MrAlex94** 2021-05-27 16:23 UTC

**Comment by zakius** [comment] 2021-05-27 19:08
> 
> 
> Either they cant be fixed now/will be fixed later, i'm favorable to it, better than let them pile up to more than 2,300 issues like on qtbittorrent. ALL devs should do a cleanup such as this one.

I'm for keeping backlog public so people are less likely to keep reporting the same issue over and over and if it won't be fixed just slap label on it, closing issues with zero communication makes community unable to contribute too

**Comment by Felipefpl** [comment] 2021-05-27 21:02
> 
> 
> > Either they cant be fixed now/will be fixed later, i'm favorable to it, better than let them pile up to more than 2,300 issues like on qtbittorrent. ALL devs should do a cleanup such as this one.
> 
> I'm for keeping backlog public so people are less likely to keep reporting the same issue over and over and if it won't be fixed just slap label on it, closing issues with zero communication makes community unable to contribute too

And it's ok, to each his own. :)

**Comment by vertigo220** [comment] 2021-05-28 00:37
It not only makes it more difficult for the community to contribute, but less likely. At the very least, some message should have been posted, whether on the main page or on the wiki, or both, so people would at least know what's going on. Just going through and closing hundreds of issues in a day without any explanation looks bad, not to mention confuses people and causes them to wonder what the heck is going on. I actually did some searching before posting this to see if Waterfox was done, since that's what it seemed like. Personally, I don't agree with it, as it seems to me like it's just taking the easy way out: too much work or too hard, just close them all and suddenly there's much less work to do, but not because anything was actually done. Basically the equivalent of just sweeping everything under a rug or cleaning a room by shoving everything in the closet.

I realize developing Waterfox is likely not Alex's job, i.e. he's probably not making much money off of it and has an actual job, and this is just a project, and I'm very thankful for the work he does on it, so don't get me wrong here, as he can ultimately do what he wants with it, but let's face it, clearing a workload by simply trashing the work isn't exactly a good way to do things. Anybody doing that at an actual job would likely not have that job for long. And when I see issues I reported go months with nothing be done on them only to then be scrapped, it makes me unlikely to contribute by reporting issues in the future, since I feel like it's just a waste of time, and I'm sure others will feel the same way. Consider also that the _vast_ majority of Waterfox users are using it instead of Firefox for a reason: because Firefox (Mozilla) just goes their own way, doing what they want, users be damned. They quit listening to their users long ago, and reporting issues to them is absolutely a waste of time. So Waterfox (Alex) doing the same thing, or even appearing to do the same thing, is going to drive away those users, because, again, that's the whole reason they're here. Anyways, that's just my .02, my perception of the situation. Take it or leave it.

**Comment by MrAlex94** [comment] 2021-05-28 09:59
> I'm for keeping backlog public so people are less likely to keep reporting the same issue over and over

I'm not - because people don't search and I closed many, many duplicates. Seems to make no difference apart from having an unorganised issue log. 

> closing issues with zero communication makes community unable to contribute too

Issues started from 4 years old. It makes no sense to keep so many open that are so outdated.

> I actually did some searching before posting this to see if Waterfox was done, since that's what it seemed like.

The project would then be archived or issues closed completely. Why would maintenance of issues make you think the project was done?

> too much work or too hard, just close them all and suddenly there's much less work to do, but not because anything was actually done

Feel free to re-open and contribute fixes. Like I said, many of the issues:

-> Either couldn't reproduce
-> Issue is too outdated
-> Issue didn't provide enough info
-> Issue isn't even an issue report
-> Classic is maintenance only unless patches provided.
-> The issue is a bug from Firefox (report to Mozilla instead).

I don't see why people want issues to be kept open? It's messy, makes it difficult looking for older issues that will be fixed (see the ones I have left open). It's not sweeping them under the rug; unless people actually bother to write up a proper issue report it's useless. And a lot where Classic issues which won't be fixed.

> I realize developing Waterfox is likely not Alex's job

It is - full time :-). But it's not an easy job and I feel as though people really have unrealistic expectations of projects such as this. What's worse is that people _expect_ things to be done for them. 

Appreciate the feedback, but I wholeheartedly disagree.
