### ISSUE TITLE
Language Pack

### ISSUE THREAD

**Issue by wbak1102** [MrAlex94/Waterfox#1929] opened 2021-02-02 19:36 UTC
There are for Waterfox G3.1.0 languages (Language Pack)

**Comment by roman6626** [comment] 2021-02-05 07:01
There is a bug in version G3.1.0. Unable to install Mozilla's language pack. Versions do not match.
In the previous version of Waterfox G3.0.2 everything is fine.
Need a quick fix!

**Comment by hawkeye116477** [comment] 2021-02-05 10:36
> Unable to install Mozilla's language pack. Need a quick fix!

It's not a bug. Mozilla's language packs will never work. You need language pack made for Waterfox. I have that packages on my repositories for Linux distros. For other OS you should wait for official packages. You can also try my packages on other OS, but it may be little problematic, cuz they haven't automatic updates.

**Comment by roman6626** [comment] 2021-02-05 13:39
And then what language packs are there?
https://github.com/MrAlex94/Waterfox/tree/future/browser/extensions

**Comment by hawkeye116477** [comment] 2021-02-05 13:51
That language packs were for older Waterfox versions and even they could appear previously working fine, some things still were missing.  Currently seems that „future" branch is not used and „current" branch is now for G3.

**Comment by roman6626** [comment] 2021-02-05 14:04
How to correctly localize Waterfox now?

**Comment by roman6626** [comment] 2021-02-05 14:14
> > Unable to install Mozilla's language pack. Need a quick fix!
> 
> It's not a bug. Mozilla's language packs will never work. You need language pack made for Waterfox. I have that packages on my repositories for Linux distros. For other OS you should wait for official packages. You can also try my packages on other OS, but it may be little problematic, cuz they haven't automatic updates (updates only work through repositories for Linux), so before updating Waterfox you'll need to install newer language pack to prevent crashing.

If localized in this way, there were untranslated pieces. The translation was incomplete and incorrect.

**Comment by hawkeye116477** [comment] 2021-02-05 14:30
> How to correctly localize Waterfox now?

Well, as I said you can try my packages from https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_16.04/all/, you need to extract them, but as I previously said it's not ideal method, cuz if something new will come in future version, then you can have crashes and you'll need to download again newer version. So I think that if you don't have Linux, then better would be to wait for official package, which might come with release of Waterfox add-on store.

**Comment by roman6626** [comment] 2021-02-05 15:00
That's just the point, I do not have Linux. I have Windows. 
Should there be an official package? When is this supposed to happen?

**Comment by hawkeye116477** [comment] 2021-02-05 15:08
Well, in commit https://github.com/MrAlex94/Waterfox/commit/1ac9a604cd4bb6a88d4cc11b0f7722353d2c3a66#diff-e2e2bd6e7f752c87ef2ae5b95050eefec36b251f621f975e8efd073d091422b8 MrAlex said `l10n is a complicated mess at the moment, needs figuring out`. I don't know what was the problem and when that will be solved. On official website it's said that on the first quarter of year Add-on store will be released, so I suppose that language packs will be soon after that.

**Comment by roman6626** [comment] 2021-02-05 15:11
**hawkeye116477**
I know you are a specialist programmer. You do Waterfox too. You will not answer the question in commit # 1926. Can't find a clear answer.
What's the difference between Waterfox Current (G3) and Firefox? Specifically on all points? How can Waterfox be better?
I would like to hear the developer's answer. I searched on Reddit but couldn't find an answer. Only different thoughts.
There is no specific information on the site either. Unfortunately.

**Comment by RJVB** [comment] 2021-02-06 19:32
I tried to get proper (erm, scuse me, GB) English spelling before looking at the issues and had to figure out how to get WF to start again without losing all my open tabs and/or settings.

No crashes but just an alert window telling me about a syntax error on line 2009 or so of a chrome/.../browser.xhtml file that I then couldn't find anywhere.

This indeed looks like a mess; in just about any other application I know the language files don't cause aborts, crashes or forced exits when they're not correct. If they're not complete, the untranslated strings (typically en-US) are shown instead.
And that's always better than no translation at all...

**Comment by jorg35** [comment] 2021-02-13 06:56
Firefox 78 is up and running and Waterfox G3.1.0 isn't there?

**Comment by MrAlex94** [comment] 2021-05-27 15:04
Languages are now integrated, unfortunately the only way to contribute is by making a [pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests). The source of the language packs is [here](https://github.com/MrAlex94/Waterfox/tree/current/browser/locales/l10n).

I'll look into creating a more efficient process, when we have enough resources - but for now this will have to do.

**Closed by MrAlex94** 2021-05-27 15:04 UTC

**Comment by RJVB** [comment] 2021-05-28 18:41
On Thursday May 27 2021 08:04:58 Alex Kontos wrote:
>Languages are now integrated

Integrated but not used according to commit #1ac9a60 . I don't know if that message has been superseded by another more recent commit in another part of the code, but I sure don't see a way to set a language other than en-US for the UI.
