### ISSUE TITLE
[Waterfox G3.2.1] Amazon.com always crashes when using any extensions.

### ISSUE THREAD

**Issue by DShip91** [MrAlex94/Waterfox#2106] opened 2021-05-28 02:21 UTC
The home page loads just fine but if you try and search for anything, the tab will automatically crash and be unable to be restored.

Even if the only extensions you use are Adblock and Noscript, the tab will still crash without fail.

The site works fine on all other browsers even with dozens of additional add-ons/extensions installed which suggests it's an issue with Waterfox and not Amazon.com itself.

**Comment by MrAlex94** [comment] 2021-05-28 10:49
I've tested on:

- macOS 11.4
- Windows 10 1H21

Cannot reproduce.

Can you reproduce in safe mode? You can access this from about:support:

![image](https://user-images.githubusercontent.com/4728920/119972977-cc6d6900-bfaa-11eb-95cb-5186a44543e4.png)

**Comment by DShip91** [comment] 2021-05-28 11:48
No I can't because safe mode disables add-ons and the website only crashes when you're using them.

**Comment by MrAlex94** [comment] 2021-05-28 12:39
What extensions/versions are you using?

**Comment by DShip91** [comment] 2021-05-28 13:21
Any extension will cause the site to crash but I use Adblocker and NoScript specifically. The site's home page loads just fine, it's only when you search that it crashes.

**Comment by MrAlex94** [comment] 2021-05-28 14:01
I've tested a few different ways, without a specific add-on to test I'll have to close this issue. I use quite a few extensions as well. Amazon is also a very popular website - if this was widespread it would be more reported.

Sometimes add-ons cause crashes. Unfortunately it'll have to be the add-on developer preventing the crash unless it can be isolated to a bug caused by the browser specifically.

**Closed as completed by MrAlex94** 2021-05-28 14:01 UTC
Labels: bug

**Comment by DShip91** [comment] 2021-05-28 22:09
I owe you an apology. It appears the issue was with MY Waterfox browser and only mine. I refreshed by settings and everything's working just fine again.

**Comment by DShip91** [comment] 2021-06-01 20:53
I just want to add to this and say that I finally found out what was causing the site to crash: If you set Waterfox to block tracking cookies _and_ isolate remaining cookies, it will cause the site to crash. This issue also affects CoolCmd's **Alternate Player for Twitch TV** extension but only when the chat is displayed for some reason.
