### ISSUE TITLE
Update caused DRM Play issues on Multiple Sites... 

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2462] opened 2021-12-02 03:17 UTC
### What happened?

When I try to watch Video on Netflix outdated Browser after update also messed up DRM with Classic Waterfox as well... 
You also over rode Autoupdate that was off... 
I had no issue with 3.2.6. now the G4 updates has 
caused play issues on TUBI, Pluto, Specturm TV online and Netflix 

Classic no longer will play stuff either I tried to roll back the Waterfox no good 

Now what do we do for Multimedia G4 has been reported with Video online issues 
Also my daughters Computer and Sons have same issue... .

You got no back up password tools , etc,

Other wise id fully delete it including directory and reinstall 3.2.6 G4 Bit and enjoy what i had as well as my kids who are in College,,, 

Why did the G4 update have to mess with anything including the classic version pertaining to DRM.... 

Please fix ASAP and also need to stop this AUTO UPDATE ask first 
Also now the G3 no longer works rolling back and Classic no longer play anything with DRM ............... 

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by guuurb** [comment] 2021-12-02 13:45
Same issue here, hope it gets fixed soon! This is a dealbreaker!

**Comment by wbak1102** [comment] 2021-12-06 06:00
For me the same ? HBO Go, Via play.
[https://github.com/WaterfoxCo/Waterfox/issues/2467](url)

**Comment by ghost** [comment] 2021-12-06 06:11
He does not work HBO Go ?

**Comment by A0R-R0CKS** [comment] 2021-12-06 06:47
In other words it also has DRM Issues playing Video on HBO website. 
Several websites with Video is having DRM issues and also gives unsupported or outdated Version of the Browser. 
It's happened to me, my Family Members and friends all using the recent Waterfox update. 
Even if you uninstall the new update and roll back to 3.6.2 that did work now it too is affected and no longer works.
The Installer automatically launches and update while installing which forces it's self to install.

**Comment by RichLuna** [comment] 2021-12-07 01:44
Seems to me the problem is caused by waterfox using an old version of widevine. An up-to-date version of firefox has widevine 4.10.2391.0 while waterfox uses 4.10.2209.1 (apparently released last september). Forcing the widevine library into waterfox seems to fix the problem.

*Workaround* (You need a working and updated version of firefox)

0. Close both firefox and waterfox.
1. Find the "libwidevinecdm.so" file in the directory {mozilla-profile}/gmp-widevinecdm/4.10.2391.0
2. Copy and replace in {waterfox-profile}/gmp-widevinecdm/4.10.2209.1

To know your current profile directory in firefox or waterfox just write "about:profiles" (without quotes) in the address bar and hit enter.

Tried this in linux and seems to be working fine. Should be the same in mac os. In windows I think the file name should have a .dll extension instead of .so.

Note that if you copy the whole plugin directory (4.10.2391.0) and copy into waterfox, it will just be ignored. Probably a clue to fix this bug.

**Comment by wbak1102** [comment] 2021-12-07 04:56
@RichLuna   it works  Thanks !  Why Alex did not do this ?

**Comment by ghost** [comment] 2021-12-07 05:01
@RichLuna Thanks !

**Comment by MrAlex94** [comment] 2021-12-07 14:17
Unsure why Widevine `4.10.2209.1` is misbehaving on certain platforms (it should still work), but commit mozilla/gecko-dev@d913610 should fix the issue. It's currently sitting in my local repo and will be available with the next release due in a few days.

**Comment by MrAlex94** [comment] 2021-12-13 09:09
Should be fixed in https://github.com/WaterfoxCo/Waterfox/commit/d913610.

**Closed as completed by MrAlex94** 2021-12-13 09:09 UTC
Labels: bug
